import type { Metadata, Viewport } from "next";
import "./globals.css";
import { BRAND } from "@/lib/brand";
import InstallPrompt from "@/components/InstallPrompt";
import ServiceWorkerRegistrar from "@/components/ServiceWorkerRegistrar";

/*
 * Deliberately not async, and it reads no cookies.
 *
 * It used to call getSession() so it could show the signed-in header. Reading
 * a cookie in the root layout opts *every page in the app* out of static
 * rendering, so the landing page, the sign-in screen and the install guide
 * were each being generated by a 28 MB serverless function in Ohio on every
 * visit — a cold start in front of the one page a new owner sees first.
 *
 * The header now lives in the (app) layout, which only wraps the signed-in
 * routes. These three public pages are plain HTML served from the CDN, and
 * the signed-in redirect that used to happen here happens in middleware, at
 * the edge, before any function runs.
 */
export const metadata: Metadata = {
  title: BRAND.name,
  description: BRAND.tagline,
  applicationName: BRAND.name,
  manifest: "/manifest.webmanifest",
  icons: {
    icon: [
      { url: "/icons/favicon-32.png", sizes: "32x32", type: "image/png" },
      { url: "/icons/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icons/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
    apple: [{ url: "/icons/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
  },
  appleWebApp: {
    capable: true,
    title: BRAND.name,
    // The app is light, so the status bar wants dark text on the page's own
    // background rather than a dark bar sitting above it.
    statusBarStyle: "default",
  },
};

export const viewport: Viewport = {
  themeColor: BRAND.themeColor,
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-screen antialiased">
        <ServiceWorkerRegistrar />
        {children}
        <InstallPrompt />
      </body>
    </html>
  );
}
