// ============================================================================
// SHARED — platform-agnostic. Imported by BOTH the web app (app/) and the
// React Native app (native/). Contains NO JSX and no platform APIs.
// Content moved VERBATIM from app/prep-a-constable.jsx — never retyped.
// ============================================================================

const FLASHCARDS = [
  { id: "fc-001", topicId: "pace-1984", q: "What does G stand for in GOWISELY?", a: "Grounds — why you are searching them" },
  { id: "fc-002", topicId: "pace-1984", q: "What does O stand for in GOWISELY?", a: "Object — what you are searching for" },
  { id: "fc-003", topicId: "pace-1984", q: "What does W stand for in GOWISELY?", a: "Warrant card — offer or show it" },
  { id: "fc-004", topicId: "pace-1984", q: "What does I stand for in GOWISELY?", a: "Identity — your name" },
  { id: "fc-005", topicId: "pace-1984", q: "What does S stand for in GOWISELY?", a: "Station — the station you are from" },
  { id: "fc-006", topicId: "pace-1984", q: "What does E stand for in GOWISELY?", a: "Entitlement — they can have a copy of the record" },
  { id: "fc-007", topicId: "pace-1984", q: "What does L stand for in GOWISELY?", a: "Law — the power you are searching under" },
  { id: "fc-008", topicId: "pace-1984", q: "What does Y stand for in GOWISELY?", a: "You are being detained for the purpose of the search" },
  { id: "fc-009", topicId: "pace-1984", q: "What does P stand for in POSH?", a: "Paint the Policing Picture — intelligence, information, tasking" },
  { id: "fc-010", topicId: "pace-1984", q: "What does O stand for in POSH?", a: "Observe — behaviour, clothing, restlessness, avoidance" },
  { id: "fc-011", topicId: "pace-1984", q: "What does S stand for in POSH?", a: "Smell — petrol, paint, drugs" },
  { id: "fc-012", topicId: "pace-1984", q: "What does H stand for in POSH?", a: "Hear — evasive answers, broken glass, alarms, shouts" },
  { id: "fc-013", topicId: "pace-1984", q: "What does the first E stand for in EEERR?", a: "Engage — approach the person professionally" },
  { id: "fc-014", topicId: "pace-1984", q: "What does the second E stand for in EEERR?", a: "Explain why you are searching — use GOWISELY and POSH" },
  { id: "fc-015", topicId: "pace-1984", q: "What does the third E stand for in EEERR?", a: "Ensure it is clear — no jargon" },
  { id: "fc-016", topicId: "pace-1984", q: "What does the first R stand for in EEERR?", a: "Record — complete the search record form; copy to the person" },
  { id: "fc-017", topicId: "pace-1984", q: "What does the second R stand for in EEERR?", a: "Reassure — stop and search protects Londoners" },
  { id: "fc-018", topicId: "pace-1984", q: "What does I stand for in IDCOPPLAN?", a: "Investigation — prompt and effective investigation of the offence" },
  { id: "fc-019", topicId: "pace-1984", q: "What does D stand for in IDCOPPLAN?", a: "Disappearance — prevent the suspect from disappearing" },
  { id: "fc-020", topicId: "pace-1984", q: "What does C stand for in IDCOPPLAN?", a: "Child or other vulnerable person — to protect them" },
  { id: "fc-021", topicId: "pace-1984", q: "What does the first P stand for in IDCOPPLAN?", a: "Physical injury — to prevent injury to self or others" },
  { id: "fc-022", topicId: "pace-1984", q: "What does the second P stand for in IDCOPPLAN?", a: "Public decency — offences against public decency" },
  { id: "fc-023", topicId: "pace-1984", q: "What does L stand for in IDCOPPLAN?", a: "Loss or damage to property" },
  { id: "fc-024", topicId: "pace-1984", q: "What does A stand for in IDCOPPLAN?", a: "Address — to confirm the person's address" },
  { id: "fc-025", topicId: "pace-1984", q: "What does N stand for in IDCOPPLAN?", a: "Name — to ascertain the person's name" },
  { id: "fc-026", topicId: "pace-1984", q: "What does O stand for in IDCOPPLAN?", a: "Obstruction of the highway" },
  { id: "fc-027", topicId: "pace-1984", q: "What does S stand for in SCARES?", a: "Save life or limb or prevent serious damage to property" },
  { id: "fc-028", topicId: "pace-1984", q: "What does C stand for in SCARES?", a: "Children — recapture a child in police protection" },
  { id: "fc-029", topicId: "pace-1984", q: "What does A stand for in SCARES?", a: "Arrest for an indictable offence" },
  { id: "fc-030", topicId: "pace-1984", q: "What does R stand for in SCARES?", a: "Recapture a person unlawfully at large" },
  { id: "fc-031", topicId: "pace-1984", q: "What does E stand for in SCARES?", a: "Execute an arrest warrant" },
  { id: "fc-032", topicId: "pace-1984", q: "What does the second S stand for in SCARES?", a: "Specified summary offences — limited list" },
  { id: "fc-033", topicId: "pace-1984", q: "What does F stand for in FILE?", a: "Forensic examination" },
  { id: "fc-034", topicId: "pace-1984", q: "What does I stand for in FILE?", a: "Investigation" },
  { id: "fc-035", topicId: "pace-1984", q: "What does L stand for in FILE?", a: "Lawful owner — to establish" },
  { id: "fc-036", topicId: "pace-1984", q: "What does E stand for in FILE?", a: "Evidence at court — to be produced" },
  { id: "fc-037", topicId: "pace-1984", q: "What does D stand for in DIE?", a: "Danger to anyone including the suspect" },
  { id: "fc-038", topicId: "pace-1984", q: "What does I stand for in DIE?", a: "Implement to escape" },
  { id: "fc-039", topicId: "pace-1984", q: "What does E stand for in DIE?", a: "Evidence of an offence" },
  { id: "fc-040", topicId: "pace-1984", q: "What does S stand for in SOAP?", a: "Stolen articles" },
  { id: "fc-041", topicId: "pace-1984", q: "What does O stand for in SOAP?", a: "Offensive weapons" },
  { id: "fc-042", topicId: "pace-1984", q: "What does A stand for in SOAP?", a: "Articles for use in burglary, theft, criminal damage, fraud or taking without consent" },
  { id: "fc-043", topicId: "pace-1984", q: "What does P stand for in SOAP?", a: "Pointed or bladed articles and fireworks" },
  { id: "fc-044", topicId: "theft-act-1968", q: "What does D stand for in DAPBI?", a: "Dishonestly — Section 2 Theft Act 1968" },
  { id: "fc-045", topicId: "theft-act-1968", q: "What does A stand for in DAPBI?", a: "Appropriates — Section 3 Theft Act 1968" },
  { id: "fc-046", topicId: "theft-act-1968", q: "What does P stand for in DAPBI?", a: "Property — Section 4 Theft Act 1968" },
  { id: "fc-047", topicId: "theft-act-1968", q: "What does B stand for in DAPBI?", a: "Belonging to another — Section 5 Theft Act 1968" },
  { id: "fc-048", topicId: "theft-act-1968", q: "What does I stand for in DAPBI?", a: "Intention of permanently depriving — Section 6 Theft Act 1968" },
  { id: "fc-049", topicId: "theft-act-1968", q: "What does W stand for in WIFE?", a: "Weapon of offence — made, adapted or intended to cause injury" },
  { id: "fc-050", topicId: "theft-act-1968", q: "What does I stand for in WIFE?", a: "Imitation firearm — anything with the appearance of a firearm" },
  { id: "fc-051", topicId: "theft-act-1968", q: "What does F stand for in WIFE?", a: "Firearm — includes airguns and air pistols" },
  { id: "fc-052", topicId: "theft-act-1968", q: "What does E stand for in WIFE?", a: "Explosive — manufactured or intended for explosive effect" },
  { id: "fc-053", topicId: "theft-act-1968", q: "What does S stand for in SID?", a: "Steal — intent to steal anything in the building" },
  { id: "fc-054", topicId: "theft-act-1968", q: "What does I stand for in SID?", a: "Inflict grievous bodily harm on any person in the building" },
  { id: "fc-055", topicId: "theft-act-1968", q: "What does D stand for in SID?", a: "Do unlawful damage to the building or anything in it" },
  { id: "fc-056", topicId: "poca-1953", q: "What does M stand for in MAI?", a: "Made for causing injury — for example a knuckle-duster" },
  { id: "fc-057", topicId: "poca-1953", q: "What does A stand for in MAI?", a: "Adapted for causing injury — for example a broken bottle" },
  { id: "fc-058", topicId: "poca-1953", q: "What does I stand for in MAI?", a: "Intended by the person to cause injury" },
  { id: "fc-059", topicId: "pace-1984", q: "What does R stand for in ROAST?", a: "Reasons — full necessity grounds and complete justification" },
  { id: "fc-060", topicId: "pace-1984", q: "What does O stand for in ROAST?", a: "Offence — the specific offence in full" },
  { id: "fc-061", topicId: "pace-1984", q: "What does A stand for in ROAST?", a: "Allegation — what the victim or witness stated" },
  { id: "fc-062", topicId: "pace-1984", q: "What does S stand for in ROAST?", a: "Summary — brief chronological account from first contact to custody" },
  { id: "fc-063", topicId: "pace-1984", q: "What does T stand for in ROAST?", a: "Time and place of arrest — exact time and exact location" },
  { id: "fc-064", topicId: "vulnerability", q: "What does A stand for in the ABCDE vulnerability assessment?", a: "Appearance — unusual, ill, injured, unsettled or anxious" },
  { id: "fc-065", topicId: "vulnerability", q: "What does B stand for in the ABCDE vulnerability assessment?", a: "Behaviour — excitable, irrational, manic, slow or furtive" },
  { id: "fc-066", topicId: "vulnerability", q: "What does C stand for in the ABCDE vulnerability assessment?", a: "Capacity and communication — speech, eye contact, understanding" },
  { id: "fc-067", topicId: "vulnerability", q: "What does D stand for in the ABCDE vulnerability assessment?", a: "Danger — risk of harm to themselves or another" },
  { id: "fc-068", topicId: "vulnerability", q: "What does E stand for in the ABCDE vulnerability assessment?", a: "Environment — time of day, living conditions, can they get home safely" },
  { id: "fc-069", topicId: "vulnerability", q: "What does A stand for in AFRAID (first letter)?", a: "Allegation — what is it and how does the victim explain it" },
  { id: "fc-070", topicId: "vulnerability", q: "What does F stand for in AFRAID?", a: "Fear — how does the suspect make them feel" },
  { id: "fc-071", topicId: "vulnerability", q: "What does R stand for in AFRAID?", a: "Reluctance — why are they reluctant to make a statement" },
  { id: "fc-072", topicId: "vulnerability", q: "What does the second A stand for in AFRAID?", a: "Adverse — what negative or harmful effect has the victim suffered" },
  { id: "fc-073", topicId: "vulnerability", q: "What does I stand for in AFRAID?", a: "Injury — detailed description of all injuries" },
  { id: "fc-074", topicId: "vulnerability", q: "What does D stand for in AFRAID?", a: "Demeanour — how is the victim presenting" },
  { id: "fc-075", topicId: "vulnerability", q: "What does S stand for in SAFEGUARD?", a: "Sexual — sexual risk, harm or wellbeing concerns" },
  { id: "fc-076", topicId: "vulnerability", q: "What does A stand for in SAFEGUARD (first letter)?", a: "Absence — absence, truancy or going missing" },
  { id: "fc-077", topicId: "vulnerability", q: "What does F stand for in SAFEGUARD?", a: "Family — family and home situation" },
  { id: "fc-078", topicId: "vulnerability", q: "What does E stand for in SAFEGUARD?", a: "Emotional — emotional and physical health" },
  { id: "fc-079", topicId: "vulnerability", q: "What does G stand for in SAFEGUARD?", a: "Gangs — gangs, street groups, age differential, involvement in crime" },
  { id: "fc-080", topicId: "vulnerability", q: "What does U stand for in SAFEGUARD?", a: "Use of technology — use of technology and sexual bullying" },
  { id: "fc-081", topicId: "vulnerability", q: "What does the second A stand for in SAFEGUARD?", a: "Alcohol — alcohol and substances" },
  { id: "fc-082", topicId: "vulnerability", q: "What does R stand for in SAFEGUARD?", a: "Receipt — receipt of unexplained gifts or money" },
  { id: "fc-083", topicId: "vulnerability", q: "What does D stand for in SAFEGUARD?", a: "Distrust — distrust of authority figures" },
  { id: "fc-084", topicId: "intelligence-mopi", q: "What does the first C stand for in CIAPOAR?", a: "Code of Ethics — at the centre of the National Decision Model" },
  { id: "fc-085", topicId: "intelligence-mopi", q: "What does I stand for in CIAPOAR?", a: "Identify powers and policy" },
  { id: "fc-086", topicId: "intelligence-mopi", q: "What does A stand for in CIAPOAR (first letter)?", a: "Aim — what are you trying to achieve" },
  { id: "fc-087", topicId: "intelligence-mopi", q: "What does P stand for in CIAPOAR?", a: "Proportionate — is the action proportionate" },
  { id: "fc-088", topicId: "intelligence-mopi", q: "What does O stand for in CIAPOAR?", a: "Options — what options are available" },
  { id: "fc-089", topicId: "intelligence-mopi", q: "What does the second A stand for in CIAPOAR?", a: "Act — take action" },
  { id: "fc-090", topicId: "intelligence-mopi", q: "What does R stand for in CIAPOAR?", a: "Review — review what happened" },
  { id: "fc-091", topicId: "disputes-noncrime", q: "What does M stand for in METHANE?", a: "Major incident declared — confirm to control room" },
  { id: "fc-092", topicId: "disputes-noncrime", q: "What does E stand for in METHANE (first letter)?", a: "Exact location — grid reference, address or landmark" },
  { id: "fc-093", topicId: "disputes-noncrime", q: "What does T stand for in METHANE?", a: "Type of incident — road traffic collision, fire, terrorism etc" },
  { id: "fc-094", topicId: "disputes-noncrime", q: "What does H stand for in METHANE?", a: "Hazards — present or suspected" },
  { id: "fc-095", topicId: "disputes-noncrime", q: "What does A stand for in METHANE?", a: "Access — routes in and out of the scene" },
  { id: "fc-096", topicId: "disputes-noncrime", q: "What does N stand for in METHANE?", a: "Numbers — casualties and types of injury" },
  { id: "fc-097", topicId: "disputes-noncrime", q: "What does the second E stand for in METHANE?", a: "Emergency services — required at scene" },
  { id: "fc-098", topicId: "da-protective", q: "What does the first R stand for in RARA?", a: "Remove — arrest or remove the threat to the victim" },
  { id: "fc-099", topicId: "da-protective", q: "What does the first A stand for in RARA?", a: "Avoid — remove the victim from the scenario" },
  { id: "fc-100", topicId: "da-protective", q: "What does the second R stand for in RARA?", a: "Reduce — reduce risk using police, support organisations and charities" },
  { id: "fc-101", topicId: "da-protective", q: "What does the second A stand for in RARA?", a: "Accept — if the victim refuses help, accept but continue to investigate" },
  { id: "fc-102", topicId: "da-protective", q: "What does D stand for in DARA?", a: "Domestic — frontline domestic abuse risk assessment tool" },
  { id: "fc-103", topicId: "da-protective", q: "What does A stand for in DARA (first letter)?", a: "Abuse — identifies subtle forms including coercive control" },
  { id: "fc-104", topicId: "da-protective", q: "What does R stand for in DARA?", a: "Risk — quality first-responder primary assessment" },
  { id: "fc-105", topicId: "da-protective", q: "What does the second A stand for in DARA?", a: "Assessment — developed by the College of Policing" },
  { id: "fc-106", topicId: "rta-1988", q: "What does A stand for in ACECARD (first letter)?", a: "Approach the scene safely and assess" },
  { id: "fc-107", topicId: "rta-1988", q: "What does C stand for in ACECARD (first letter)?", a: "Caution signs — place warning signs or cones" },
  { id: "fc-108", topicId: "rta-1988", q: "What does E stand for in ACECARD?", a: "Examine the scene — visual assessment of scene and hazards" },
  { id: "fc-109", topicId: "rta-1988", q: "What does the second C stand for in ACECARD?", a: "Casualties — identify and prioritise casualties" },
  { id: "fc-110", topicId: "rta-1988", q: "What does the second A stand for in ACECARD?", a: "Ambulance, fire rescue and other partnership agencies — call them in" },
  { id: "fc-111", topicId: "rta-1988", q: "What does R stand for in ACECARD?", a: "Remove obstructions — clear the scene where safe" },
  { id: "fc-112", topicId: "rta-1988", q: "What does D stand for in ACECARD?", a: "Detailed investigation — statements, evidence, documentation" },
  { id: "fc-113", topicId: "pace-1984", q: "What does S stand for in STAIRS (first letter)?", a: "Statements in direct speech — exact words in quotation marks" },
  { id: "fc-114", topicId: "pace-1984", q: "What does T stand for in STAIRS?", a: "Times — exact times for every action and observation" },
  { id: "fc-115", topicId: "pace-1984", q: "What does A stand for in STAIRS?", a: "Actions taken — every action and why, with legal justification" },
  { id: "fc-116", topicId: "pace-1984", q: "What does I stand for in STAIRS?", a: "Information given — what information, from whom, at what time" },
  { id: "fc-117", topicId: "pace-1984", q: "What does R stand for in STAIRS?", a: "Referrals — every person you handed information or persons to" },
  { id: "fc-118", topicId: "pace-1984", q: "What does the second S stand for in STAIRS?", a: "Supervisor informed — when and what direction they gave" },
  { id: "fc-119", topicId: "pace-1984", q: "What does E stand for in NO ELBOWS?", a: "Erasures — none; use a single line through mistakes" },
  { id: "fc-120", topicId: "pace-1984", q: "What does L stand for in NO ELBOWS?", a: "Leaves torn out — none; no pages removed" },
  { id: "fc-121", topicId: "pace-1984", q: "What does B stand for in NO ELBOWS?", a: "Blank spaces — none; no empty gaps" },
  { id: "fc-122", topicId: "pace-1984", q: "What does O stand for in NO ELBOWS (second letter)?", a: "Overwriting — none; do not write over existing words" },
  { id: "fc-123", topicId: "pace-1984", q: "What does W stand for in NO ELBOWS?", a: "Writing in margins or between lines — none" },
  { id: "fc-124", topicId: "pace-1984", q: "What does the second S stand for in NO ELBOWS?", a: "Statements in direct speech — record exact words used" },
  { id: "fc-125", topicId: "vulnerability", q: "What does P stand for in PENS?", a: "Physical abuse — hitting, shaking, throwing, burning, suffocating" },
  { id: "fc-126", topicId: "vulnerability", q: "What does E stand for in PENS?", a: "Emotional abuse — persistent maltreatment, humiliating, isolating" },
  { id: "fc-127", topicId: "vulnerability", q: "What does N stand for in PENS?", a: "Neglect — persistent failure to meet basic physical or psychological needs" },
  { id: "fc-128", topicId: "vulnerability", q: "What does S stand for in PENS?", a: "Sexual abuse — forcing or enticing a child into sexual activities" },
  { id: "fc-129", topicId: "vulnerability", q: "What does F stand for in FOUR?", a: "Fixated — intense unhealthy preoccupation with the victim" },
  { id: "fc-130", topicId: "vulnerability", q: "What does O stand for in FOUR?", a: "Obsessive — compulsive and persistent despite warnings" },
  { id: "fc-131", topicId: "vulnerability", q: "What does U stand for in FOUR?", a: "Unwanted — all contact clearly unwelcome" },
  { id: "fc-132", topicId: "vulnerability", q: "What does R stand for in FOUR?", a: "Repeated — occurs on multiple occasions forming a pattern" },
  { id: "fc-133", topicId: "rta-1988", q: "What does P stand for in PRIMROSE?", a: "Position of vehicles — where vehicles ended up after the collision" },
  { id: "fc-134", topicId: "rta-1988", q: "What does R stand for in PRIMROSE (first letter)?", a: "Record of questions and answers" },
  { id: "fc-135", topicId: "rta-1988", q: "What does I stand for in PRIMROSE?", a: "Information to local authority — damage to fixed property requires notification" },
  { id: "fc-136", topicId: "rta-1988", q: "What does M stand for in PRIMROSE?", a: "Marks and debris on road — skid marks, glass, vehicle parts" },
  { id: "fc-137", topicId: "rta-1988", q: "What does the second R stand for in PRIMROSE?", a: "Removal of vehicles — recovery arrangements and timings" },
  { id: "fc-138", topicId: "rta-1988", q: "What does O stand for in PRIMROSE?", a: "Offences committed or alleged at the scene" },
  { id: "fc-139", topicId: "rta-1988", q: "What does S stand for in PRIMROSE?", a: "Supervisor informed" },
  { id: "fc-140", topicId: "rta-1988", q: "What does E stand for in PRIMROSE?", a: "Exchange of names and addresses — driver and witness details" },
  { id: "fc-141", topicId: "intelligence-mopi", q: "What does S stand for in SARA?", a: "Scanning — identify and define the problem" },
  { id: "fc-142", topicId: "intelligence-mopi", q: "What does A stand for in SARA (first letter)?", a: "Analysis — examine the problem in depth" },
  { id: "fc-143", topicId: "intelligence-mopi", q: "What does R stand for in SARA?", a: "Response — develop and implement responses" },
  { id: "fc-144", topicId: "intelligence-mopi", q: "What does the second A stand for in SARA?", a: "Assessment — evaluate the effectiveness of the responses" },
  { id: "fc-145", topicId: "intelligence-mopi", q: "What does C stand for in CRAVED?", a: "Concealable — easy to hide" },
  { id: "fc-146", topicId: "intelligence-mopi", q: "What does R stand for in CRAVED?", a: "Removable — easy to carry away" },
  { id: "fc-147", topicId: "intelligence-mopi", q: "What does A stand for in CRAVED?", a: "Available — easy to access or commonly found" },
  { id: "fc-148", topicId: "intelligence-mopi", q: "What does V stand for in CRAVED?", a: "Valuable — worth money or useful to the offender" },
  { id: "fc-149", topicId: "intelligence-mopi", q: "What does E stand for in CRAVED?", a: "Enjoyable — desirable for personal use or status" },
  { id: "fc-150", topicId: "intelligence-mopi", q: "What does D stand for in CRAVED?", a: "Disposable — easy to sell or get rid of" },
  { id: "fc-151", topicId: "missing-persons", q: "What does C stand for in the Mental Capacity Act 2005 assessment (CURE)?", a: "Communicate — can the person communicate their decision" },
  { id: "fc-152", topicId: "missing-persons", q: "What does U stand for in the CURE test?", a: "Understand — can they understand the relevant information" },
  { id: "fc-153", topicId: "missing-persons", q: "What does R stand for in the CURE test?", a: "Retain — can they retain the information long enough to decide" },
  { id: "fc-154", topicId: "missing-persons", q: "What does E stand for in the CURE test?", a: "Evaluate — can they weigh the information to make a decision" },
  { id: "fc-155", topicId: "pace-1984", q: "What does A stand for in the ABCDE detainee risk assessment at custody?", a: "Appearance — visible injuries, intoxication, self-harm, physical condition" },
  { id: "fc-156", topicId: "pace-1984", q: "What does B stand for in the ABCDE detainee risk assessment?", a: "Behaviour — aggressive, agitated, confused, withdrawn or compliant" },
  { id: "fc-157", topicId: "pace-1984", q: "What does C stand for in the ABCDE detainee risk assessment?", a: "Communication — coherent, slurred, language barrier, capacity" },
  { id: "fc-158", topicId: "pace-1984", q: "What does D stand for in the ABCDE detainee risk assessment?", a: "Danger — risk to themselves or to others" },
  { id: "fc-159", topicId: "pace-1984", q: "What does E stand for in the ABCDE detainee risk assessment?", a: "Environment — time of day, vulnerability if bailed, can they get home safely" },
  { id: "fc-160", topicId: "suspect-interviews", q: "What does P stand for in PEACE?", a: "Plan and prepare" },
  { id: "fc-161", topicId: "suspect-interviews", q: "What does E stand for in PEACE (first letter)?", a: "Engage and explain" },
  { id: "fc-162", topicId: "suspect-interviews", q: "What does A stand for in PEACE?", a: "Account — take the account" },
  { id: "fc-163", topicId: "suspect-interviews", q: "What does C stand for in PEACE?", a: "Closure" },
  { id: "fc-164", topicId: "suspect-interviews", q: "What does the second E stand for in PEACE?", a: "Evaluate" },
  { id: "fc-165", topicId: "suspect-interviews", q: "What does T stand for in TEDSPIE?", a: "Tell me everything you remember" },
  { id: "fc-166", topicId: "suspect-interviews", q: "What does E stand for in TEDSPIE (first letter)?", a: "Explain" },
  { id: "fc-167", topicId: "suspect-interviews", q: "What does D stand for in TEDSPIE?", a: "Describe" },
  { id: "fc-168", topicId: "suspect-interviews", q: "What does S stand for in TEDSPIE?", a: "Show me — drawing or demonstration" },
  { id: "fc-169", topicId: "suspect-interviews", q: "What does P stand for in TEDSPIE?", a: "Precisely" },
  { id: "fc-170", topicId: "suspect-interviews", q: "What does I stand for in TEDSPIE?", a: "In as much detail" },
  { id: "fc-171", topicId: "suspect-interviews", q: "What does the second E stand for in TEDSPIE?", a: "Exactly" },
  { id: "fc-172", topicId: "suspect-interviews", q: "What does A stand for in ADVOKATE?", a: "Amount of time the witness observed the suspect" },
  { id: "fc-173", topicId: "suspect-interviews", q: "What does D stand for in ADVOKATE?", a: "Distance from the suspect" },
  { id: "fc-174", topicId: "suspect-interviews", q: "What does V stand for in ADVOKATE?", a: "Visibility — lighting, weather conditions" },
  { id: "fc-175", topicId: "suspect-interviews", q: "What does O stand for in ADVOKATE?", a: "Obstructions between witness and suspect" },
  { id: "fc-176", topicId: "suspect-interviews", q: "What does K stand for in ADVOKATE?", a: "Known before — did the witness know the suspect previously" },
  { id: "fc-177", topicId: "suspect-interviews", q: "What does A stand for in ADVOKATE (second letter)?", a: "Any particular reason to remember — distinctive features" },
  { id: "fc-178", topicId: "suspect-interviews", q: "What does T stand for in ADVOKATE?", a: "Time lapse since the incident" },
  { id: "fc-179", topicId: "suspect-interviews", q: "What does E stand for in ADVOKATE?", a: "Errors or discrepancies in the description" },
  { id: "fc-180", topicId: "rta-1988", q: "What does the first P stand for in PIPES?", a: "Particulars not exchanged at a collision" },
  { id: "fc-181", topicId: "rta-1988", q: "What does I stand for in PIPES?", a: "Injury or death — person other than the driver injured or killed" },
  { id: "fc-182", topicId: "rta-1988", q: "What does the second P stand for in PIPES?", a: "Police collision — a police vehicle was involved" },
  { id: "fc-183", topicId: "rta-1988", q: "What does E stand for in PIPES?", a: "Evidence of offences — independent evidence or witnesses present" },
  { id: "fc-184", topicId: "rta-1988", q: "What does S stand for in PIPES?", a: "Special circumstances — diplomat involved or unusual nature" },
  { id: "fc-185", topicId: "vulnerability", q: "What does T stand for in THRIVE+?", a: "Threat — what is the threat and how immediate" },
  { id: "fc-186", topicId: "vulnerability", q: "What does H stand for in THRIVE+?", a: "Harm — what harm has been or could be caused" },
  { id: "fc-187", topicId: "vulnerability", q: "What does R stand for in THRIVE+?", a: "Risk — how likely is the harm and how serious" },
  { id: "fc-188", topicId: "vulnerability", q: "What does I stand for in THRIVE+?", a: "Investigation — what investigative opportunities exist" },
  { id: "fc-189", topicId: "vulnerability", q: "What does V stand for in THRIVE+?", a: "Vulnerability — are any persons involved vulnerable" },
  { id: "fc-190", topicId: "vulnerability", q: "What does E stand for in THRIVE+?", a: "Engagement — what level of engagement does this require" },
  { id: "fc-191", topicId: "pace-1984", q: "Which section of the Police and Criminal Evidence Act 1984 gives the power to stop and search in a public place?", a: "Section 1" },
  { id: "fc-192", topicId: "pace-1984", q: "Which section gives the power of entry to save life or limb?", a: "Section 17" },
  { id: "fc-193", topicId: "pace-1984", q: "Which section gives the power to search premises after arrest for an indictable offence?", a: "Section 18 — requires Inspector authorisation" },
  { id: "fc-194", topicId: "pace-1984", q: "Which section gives the power to seize anything on premises when lawfully present?", a: "Section 19" },
  { id: "fc-195", topicId: "pace-1984", q: "Which section gives the power to retain seized items?", a: "Section 22" },
  { id: "fc-196", topicId: "pace-1984", q: "Which section gives the constable's power of arrest without warrant?", a: "Section 24" },
  { id: "fc-197", topicId: "pace-1984", q: "Which section governs citizen's arrest?", a: "Section 24A" },
  { id: "fc-198", topicId: "pace-1984", q: "Which section gives the power to search a person upon arrest?", a: "Section 32" },
  { id: "fc-199", topicId: "pace-1984", q: "Which section gives the custody officer the power to search on arrival at the station?", a: "Section 54" },
  { id: "fc-200", topicId: "pace-1984", q: "Which section authorises use of reasonable force when exercising Police and Criminal Evidence Act 1984 powers?", a: "Section 117" },
  { id: "fc-201", topicId: "pace-1984", q: "What is the threshold for Section 17 entry to arrest — suspicion or belief?", a: "Belief — higher than suspicion because entry is a significant intrusion" },
  { id: "fc-202", topicId: "pace-1984", q: "What is the threshold for Section 17(1)(e) entry to save life?", a: "Suspicion only — does not require belief that a person is on the premises" },
  { id: "fc-203", topicId: "pace-1984", q: "Which Police and Criminal Evidence Act 1984 Code covers stop and search?", a: "Code A" },
  { id: "fc-204", topicId: "pace-1984", q: "Which Police and Criminal Evidence Act 1984 Code covers search of premises and seizure?", a: "Code B" },
  { id: "fc-205", topicId: "pace-1984", q: "Which Police and Criminal Evidence Act 1984 Code covers detention, treatment and questioning?", a: "Code C" },
  { id: "fc-206", topicId: "pace-1984", q: "Which Police and Criminal Evidence Act 1984 Code covers identification of persons?", a: "Code D" },
  { id: "fc-207", topicId: "pace-1984", q: "Which Police and Criminal Evidence Act 1984 Code covers audio recording of suspect interviews?", a: "Code E" },
  { id: "fc-208", topicId: "pace-1984", q: "Which Police and Criminal Evidence Act 1984 Code covers video recording of suspect interviews?", a: "Code F" },
  { id: "fc-209", topicId: "pace-1984", q: "Which Police and Criminal Evidence Act 1984 Code covers statutory powers of arrest?", a: "Code G" },
  { id: "fc-210", topicId: "pace-1984", q: "Which Police and Criminal Evidence Act 1984 Code covers terrorism detention?", a: "Code H — for arrests under Section 41 Terrorism Act 2000" },
  { id: "fc-211", topicId: "pace-1984", q: "What are the maximum detention periods without charge?", a: "24 hours standard, extended to 36 by Superintendent, up to 96 by Magistrate warrant" },
  { id: "fc-212", topicId: "pace-1984", q: "What is the two-part test for a lawful arrest under Section 24?", a: "Reasonable grounds to suspect an offence AND a necessity ground from IDCOPPLAN" },
  { id: "fc-213", topicId: "pace-1984", q: "What are the three things Caution Plus Three tells the person?", a: "Not under arrest, free to leave at any time, entitled to free legal advice" },
  { id: "fc-214", topicId: "theft-act-1968", q: "What is the maximum sentence for robbery under Section 8 Theft Act 1968?", a: "Life imprisonment" },
  { id: "fc-215", topicId: "theft-act-1968", q: "What is the mode of trial for theft under Section 1 Theft Act 1968?", a: "Either-way" },
  { id: "fc-216", topicId: "theft-act-1968", q: "Is a horse a conveyance under Section 12 Theft Act 1968?", a: "No — Neal v Gribble 1978: a horse is not constructed for the carriage of a person" },
  { id: "fc-217", topicId: "theft-act-1968", q: "Is a pedal cycle covered by Section 12 Theft Act 1968?", a: "No — pedal cycles are excluded; they have their own offence under Section 12(5)" },
  { id: "fc-218", topicId: "theft-act-1968", q: "What distinguishes taking without consent from theft?", a: "Taking without consent requires no intention to permanently deprive — theft does" },
  { id: "fc-219", topicId: "theft-act-1968", q: "Under Section 9(1)(a) Theft Act 1968, does the offender need to actually steal anything?", a: "No — entering as a trespasser with intent is enough; the offence is complete on entry" },
  { id: "fc-220", topicId: "theft-act-1968", q: "Under Section 9(1)(b) Theft Act 1968, does the offender need intent to steal on entry?", a: "No — the theft or grievous bodily harm just needs to occur after entering as a trespasser" },
  { id: "fc-221", topicId: "theft-act-1968", q: "For aggravated burglary, when must the offender have the weapon?", a: "At the time of the burglary — picking one up inside still counts" },
  { id: "fc-222", topicId: "theft-act-1968", q: "What is the maximum sentence for aggravated burglary?", a: "Life imprisonment" },
  { id: "fc-223", topicId: "theft-act-1968", q: "Under Section 25 Going Equipped, does the intended burglary need to have happened?", a: "No — preparatory offence; at home equals not guilty" },
  { id: "fc-224", topicId: "theft-act-1968", q: "What is the key case on robbery and dishonesty?", a: "R v Robinson 1977 — no dishonesty proved means no theft, so no robbery" },
  { id: "fc-225", topicId: "moda-1971", q: "Is cannabis Class A, B or C under the Misuse of Drugs Act 1971?", a: "Class B" },
  { id: "fc-226", topicId: "moda-1971", q: "Is heroin Class A, B or C?", a: "Class A" },
  { id: "fc-227", topicId: "moda-1971", q: "Is ketamine Class A, B or C?", a: "Class B" },
  { id: "fc-228", topicId: "moda-1971", q: "Is GHB Class A, B or C?", a: "Class C" },
  { id: "fc-229", topicId: "moda-1971", q: "Which section of the Misuse of Drugs Act 1971 covers production and supply?", a: "Section 4" },
  { id: "fc-230", topicId: "moda-1971", q: "Which section covers possession and possession with intent to supply?", a: "Section 5" },
  { id: "fc-231", topicId: "moda-1971", q: "Does a person need to profit from supply under Section 4 Misuse of Drugs Act 1971?", a: "No — giving drugs away freely is still supply; sharing a joint is supply" },
  { id: "fc-232", topicId: "moda-1971", q: "What does constructive possession mean?", a: "The drug does not need to be physically in hand — knowing it is there with control is sufficient" },
  { id: "fc-233", topicId: "moda-1971", q: "Which section gives the power to search for drugs without a warrant?", a: "Section 23 Misuse of Drugs Act 1971 — for a person or vehicle" },
  { id: "fc-234", topicId: "moda-1971", q: "Does Section 23 require a warrant to search premises?", a: "Yes — Section 23(3) requires a warrant to enter and search premises" },
  { id: "fc-235", topicId: "poca-1953", q: "What is the maximum cutting-edge length of a folding pocket knife that is exempt from Section 139 Criminal Justice Act 1988?", a: "Three inches — and it must not lock" },
  { id: "fc-236", topicId: "poca-1953", q: "Where is possession of a flick knife or gravity knife illegal?", a: "Anywhere — public or private, including inside the home" },
  { id: "fc-237", topicId: "poca-1953", q: "Where is possession of a corrosive substance an offence?", a: "In a public place — under Section 6 Offensive Weapons Act 2019" },
  { id: "fc-238", topicId: "cja-1988", q: "Which section covers possession of a bladed or pointed article in a public place?", a: "Section 139 Criminal Justice Act 1988" },
  { id: "fc-239", topicId: "cja-1988", q: "Which section gives the power to enter school premises to search for bladed articles?", a: "Section 139B Criminal Justice Act 1988" },
  { id: "fc-240", topicId: "poa-1986", q: "How many people are required for riot under Section 1 Public Order Act 1986?", a: "Twelve or more" },
  { id: "fc-241", topicId: "poa-1986", q: "How many people are required for violent disorder under Section 2?", a: "Three or more" },
  { id: "fc-242", topicId: "poa-1986", q: "Can affray under Section 3 Public Order Act 1986 be committed by one person?", a: "Yes" },
  { id: "fc-243", topicId: "poa-1986", q: "What is the maximum sentence for riot?", a: "Ten years — indictable only" },
  { id: "fc-244", topicId: "poa-1986", q: "What is the maximum sentence for violent disorder?", a: "Five years — either-way" },
  { id: "fc-245", topicId: "poa-1986", q: "What is the maximum sentence for affray?", a: "Three years — either-way" },
  { id: "fc-246", topicId: "poa-1986", q: "What is the mode of trial and penalty for Section 5 Public Order Act 1986?", a: "Summary only — level three fine, no imprisonment" },
  { id: "fc-247", topicId: "poa-1986", q: "Does Section 5 Public Order Act 1986 still include the word insulting?", a: "No — insulting was removed in 2014; Section 5 now covers only threatening or abusive" },
  { id: "fc-248", topicId: "poa-1986", q: "Does Section 4 Public Order Act 1986 include insulting?", a: "Yes — Section 4 still includes threatening, abusive or insulting words or behaviour" },
  { id: "fc-249", topicId: "poa-1986", q: "For Section 1 Riot, must the defendant use or just threaten unlawful violence?", a: "Must actually use — merely threatening is not enough for riot" },
  { id: "fc-250", topicId: "poa-1986", q: "Can affray be committed in a private place?", a: "Yes — public or private place" },
  { id: "fc-251", topicId: "poa-1986", q: "For Section 3 Affray, can mere words alone constitute the offence?", a: "No — there must be conduct as well as words" },
  { id: "fc-252", topicId: "crim-damage-1971", q: "What is the financial threshold that changes criminal damage from summary to either-way?", a: "Over five thousand pounds makes it either-way; five thousand or less is summary only" },
  { id: "fc-253", topicId: "crim-damage-1971", q: "Does Section 1(2) Criminal Damage Act 1971 require the property to belong to another person?", a: "No — the property can belong to the offender themselves" },
  { id: "fc-254", topicId: "crim-damage-1971", q: "What is the maximum sentence for Section 1(2) aggravated criminal damage?", a: "Life imprisonment — indictable only" },
  { id: "fc-255", topicId: "crim-damage-1971", q: "Does the lawful excuse defence in Section 5 apply to Section 1(2)?", a: "No — Section 5 lawful excuse does not apply where life is endangered" },
  { id: "fc-256", topicId: "crim-damage-1971", q: "Must a belief in lawful excuse be reasonable to succeed?", a: "No — it only needs to be honestly held" },
  { id: "fc-257", topicId: "asbcp-2014", q: "What rank authorises a dispersal zone under Section 34 Anti-Social Behaviour, Crime and Policing Act 2014?", a: "Inspector or above" },
  { id: "fc-258", topicId: "asbcp-2014", q: "What is the maximum duration of a dispersal authorisation under Section 34?", a: "Forty-eight hours" },
  { id: "fc-259", topicId: "asbcp-2014", q: "Must a dispersal direction be given in writing?", a: "Yes — in writing, unless impracticable, then orally with a written record as soon as practicable" },
  { id: "fc-260", topicId: "asbcp-2014", q: "Can a dispersal direction be given to a person under ten years old?", a: "No — Section 36 prohibits this" },
  { id: "fc-261", topicId: "asbcp-2014", q: "What must happen to a person under sixteen who is dispersed?", a: "They must be taken home or to a place of safety" },
  { id: "fc-262", topicId: "asbcp-2014", q: "What is the offence for failing to comply with a dispersal direction?", a: "Section 39 Anti-Social Behaviour, Crime and Policing Act 2014 — summary only, maximum three months" },
  { id: "fc-263", topicId: "rta-1988", q: "What are the four possible outcomes of a roadside Electronic Screening Device test?", a: "Zero, Pass, Warn, Fail" },
  { id: "fc-264", topicId: "rta-1988", q: "How long before an Electronic Screening Device test must the driver not have consumed alcohol?", a: "Twenty minutes" },
  { id: "fc-265", topicId: "rta-1988", q: "How long before an Electronic Screening Device test must the driver not have smoked or vaped?", a: "Five minutes" },
  { id: "fc-266", topicId: "rta-1988", q: "What is the arrest wording after a Fail result on a roadside Electronic Screening Device test?", a: "I am arresting you because the breath test is positive and because I suspect you of driving having had too much to drink" },
  { id: "fc-267", topicId: "rta-1988", q: "What should happen immediately after the arrest wording on a Fail result?", a: "Give the caution and record any response and the time of arrest" },
  { id: "fc-268", topicId: "rta-1988", q: "Which section of the Road Traffic Act 1988 requires a driver to stop?", a: "Section 163" },
  { id: "fc-269", topicId: "rta-1988", q: "Which section requires a driver to produce a licence?", a: "Section 164" },
  { id: "fc-270", topicId: "rta-1988", q: "Which section covers preliminary breath, impairment and drug tests?", a: "Section 6" },
  { id: "fc-271", topicId: "rta-1988", q: "Which section covers failure to stop and failure to report a collision?", a: "Section 170" },
  { id: "fc-272", topicId: "rta-1988", q: "What is the mode of trial for dangerous driving under Section 2 Road Traffic Act 1988?", a: "Indictable only" },
  { id: "fc-273", topicId: "rta-1988", q: "What is the mode of trial for careless driving under Section 3?", a: "Summary only" },
  { id: "fc-280", topicId: "oap-1861", q: "Which section and Act covers common assault?", a: "Section 39 Criminal Justice Act 1988" },
  { id: "fc-281", topicId: "oap-1861", q: "Which section and Act covers actual bodily harm?", a: "Section 47 Offences Against the Person Act 1861" },
  { id: "fc-282", topicId: "oap-1861", q: "Which section and Act covers grievous bodily harm without intent?", a: "Section 20 Offences Against the Person Act 1861" },
  { id: "fc-283", topicId: "oap-1861", q: "Which section and Act covers grievous bodily harm with intent?", a: "Section 18 Offences Against the Person Act 1861 — maximum life" },
  { id: "fc-284", topicId: "oap-1861", q: "What is the mode of trial for Section 39 common assault?", a: "Summary only" },
  { id: "fc-285", topicId: "oap-1861", q: "What is the mode of trial for Section 47 actual bodily harm?", a: "Either-way" },
  { id: "fc-286", topicId: "oap-1861", q: "What is the mode of trial for Section 18 grievous bodily harm with intent?", a: "Indictable only" },
  { id: "fc-287", topicId: "oap-1861", q: "What is the test for whether an injury amounts to actual bodily harm?", a: "More than transient and trifling — from R v Donovan 1934" },
  { id: "fc-288", topicId: "oap-1861", q: "What does wounding require under Section 20 or Section 18?", a: "All layers of the skin must be broken — both dermis and epidermis" },
  { id: "fc-289", topicId: "oap-1861", q: "What is the key distinction in mens rea between Section 20 and Section 18?", a: "Section 20 requires only malice or recklessness as to some harm; Section 18 requires specific intent to cause grievous bodily harm or resist arrest" },
  { id: "fc-290", topicId: "oap-1861", q: "Is Section 1 of the Assaults on Emergency Workers (Offences) Act 2018 summary only or either-way?", a: "Either-way — an uplift from Section 39 Criminal Justice Act 1988 which is summary only" },
  { id: "fc-291", topicId: "oap-1861", q: "Can voluntary intoxication be a defence to Section 18 grievous bodily harm with intent?", a: "Possibly — it may be relevant to whether the specific intent could be formed" },
  { id: "fc-292", topicId: "oap-1861", q: "Can a parent use reasonable chastisement as a defence to actual bodily harm?", a: "No — only up to the level of common assault" },
  { id: "fc-293", topicId: "soa-2003", q: "What is the age of consent to sexual activity in England and Wales?", a: "Sixteen" },
  { id: "fc-294", topicId: "soa-2003", q: "Can a child under thirteen consent to sexual activity?", a: "No — they are automatically regarded as unable to consent" },
  { id: "fc-295", topicId: "soa-2003", q: "What are the two key words in the Section 74 Sexual Offences Act 2003 definition of consent?", a: "Choice and freedom" },
  { id: "fc-296", topicId: "soa-2003", q: "What type of presumptions does Section 75 Sexual Offences Act 2003 create?", a: "Evidential — rebuttable presumptions" },
  { id: "fc-297", topicId: "soa-2003", q: "What type of presumptions does Section 76 Sexual Offences Act 2003 create?", a: "Conclusive — unrebuttable presumptions" },
  { id: "fc-298", topicId: "soa-2003", q: "What are the two Section 76 circumstances?", a: "Deception as to the nature or purpose of the act, and impersonation of a person known personally to the victim" },
  { id: "fc-299", topicId: "soa-2003", q: "What is the key case for Section 76 deception as to nature or purpose?", a: "R v Flattery 1877 — defendant claimed a sexual act was a surgical procedure" },
  { id: "fc-300", topicId: "soa-2003", q: "Is being asleep a Section 75 or Section 76 circumstance?", a: "Section 75 — evidential, rebuttable" },
  { id: "fc-301", topicId: "soa-2003", q: "What is the maximum sentence for Section 5 rape of a child under thirteen?", a: "Life imprisonment" },
  { id: "fc-302", topicId: "soa-2003", q: "Who can administer an Early Evidence Kit?", a: "Any trained officer — not only detectives or specialist rape and serious sexual offences officers" },
  { id: "fc-303", topicId: "soa-2003", q: "After the mouth swab in an Early Evidence Kit, what comes next?", a: "The mouth wash — in that order" },
  { id: "fc-304", topicId: "vulnerability", q: "What is the College of Policing 2020 definition of a vulnerable person?", a: "A person unable to take care of or protect themselves or others from harm or exploitation as a result of their situation or circumstances" },
  { id: "fc-305", topicId: "vulnerability", q: "Which Act places the safeguarding duty on the local authority?", a: "Care Act 2014 — Section 42" },
  { id: "fc-306", topicId: "vulnerability", q: "What are the three Care Act 2014 Section 42 triggers?", a: "Has needs for care and support, is experiencing or at risk of abuse or neglect, and is unable to protect themselves as a result" },
  { id: "fc-307", topicId: "vulnerability", q: "What is the maximum sentence for controlling or coercive behaviour under Section 76 Serious Crime Act 2015?", a: "Five years" },
  { id: "fc-308", topicId: "da-protective", q: "What rank authorises a Domestic Violence Protection Notice?", a: "Superintendent or above" },
  { id: "fc-309", topicId: "da-protective", q: "Within how many hours of serving a Domestic Violence Protection Notice must police apply to court for a Domestic Violence Protection Order?", a: "Forty-eight hours" },
  { id: "fc-310", topicId: "da-protective", q: "How long can a Domestic Violence Protection Order last?", a: "Minimum fourteen days, maximum twenty-eight days" },
  { id: "fc-311", topicId: "da-protective", q: "Under which section and Act is a Non-Molestation Order made?", a: "Section 42 Family Law Act 1996" },
  { id: "fc-312", topicId: "da-protective", q: "Is breach of a Non-Molestation Order a civil or criminal matter?", a: "Criminal — Section 42A Family Law Act 1996, maximum five years" },
  { id: "fc-313", topicId: "da-protective", q: "Under which section and Act is a Restraining Order made?", a: "Section 360 Sentencing Act 2020 — can be made post-conviction or on acquittal" },
  { id: "fc-314", topicId: "da-protective", q: "What are the two limbs of the Domestic Violence Disclosure Scheme?", a: "Right to Ask — public applies to police; Right to Know — police proactively disclose without request" },
  { id: "fc-315", topicId: "rr-aggravated", q: "Which two protected characteristics can lead to a racially or religiously aggravated offence under the Crime and Disorder Act 1998?", a: "Race and religion only" },
  { id: "fc-316", topicId: "rr-aggravated", q: "What characteristics does Section 66 Sentencing Act 2020 cover in addition to race and religion?", a: "Disability, sexual orientation, and transgender identity" },
  { id: "fc-317", topicId: "rr-aggravated", q: "Can Section 18 grievous bodily harm with intent be charged as racially aggravated under the Crime and Disorder Act 1998?", a: "No — Section 29 only applies to common assault, actual bodily harm and Section 20" },
  { id: "fc-318", topicId: "rr-aggravated", q: "Does a Section 28 Crime and Disorder Act 1998 aggravated offence require the victim to actually be a member of the racial or religious group?", a: "No — presumed membership is sufficient" },
  { id: "fc-319", topicId: "missing-persons", q: "What is the College of Policing definition of a missing person?", a: "Anyone whose whereabouts cannot be established until located and their wellbeing confirmed" },
  { id: "fc-320", topicId: "missing-persons", q: "What are the three missing person risk levels?", a: "Standard or low, medium, and high" },
  { id: "fc-321", topicId: "missing-persons", q: "Does age alone determine the risk level for a missing child?", a: "No — children can be standard or low risk if justified by the circumstances" },
  { id: "fc-322", topicId: "missing-persons", q: "What is the maximum duration of police protection under Section 46 Children Act 1989?", a: "Seventy-two hours" },
  { id: "fc-323", topicId: "missing-persons", q: "Does Section 46 Children Act 1989 include a power to use force?", a: "No — force must be justified under Section 3 Criminal Law Act 1967 or common law" },
  { id: "fc-324", topicId: "missing-persons", q: "Which section of the Mental Health Act 1983 applies in public places?", a: "Section 136 — not applicable inside a private dwelling" },
  { id: "fc-325", topicId: "missing-persons", q: "Which section of the Mental Health Act 1983 requires a warrant to enter a private dwelling?", a: "Section 135 — executed with mental health professionals" },
  { id: "fc-326", topicId: "case-files-mg", q: "What does MG3 stand for?", a: "Report to the Crown Prosecution Service for a charging decision" },
  { id: "fc-327", topicId: "case-files-mg", q: "What is the difference between MG3 and MG5?", a: "MG3 is for the prosecutor and can contain confidential information; MG5 is the case summary for the defence with confidential information removed" },
  { id: "fc-328", topicId: "case-files-mg", q: "What does MG6D contain?", a: "The schedule of sensitive unused material — provided to the Crown Prosecution Service only, not shown to the defence" },
  { id: "fc-329", topicId: "case-files-mg", q: "What does the SDC replace at magistrates' court level?", a: "MG6C and MG6E — but sensitive material still goes on an MG6D regardless" },
  { id: "fc-330", topicId: "case-files-mg", q: "What has replaced the MG20?", a: "MG6 Continuation — officers should not use MG20" },
  { id: "fc-331", topicId: "case-files-mg", q: "What is the MG21 used for?", a: "Forensic submission — must accompany all evidence or samples sent for testing" },
  { id: "fc-332", topicId: "case-files-mg", q: "What are the three unused material assessment answers on the MG3?", a: "They must be written word for word as set out in the Director's Guidance on Charging — wrong wording means file rejected" },
  { id: "fc-333", topicId: "case-files-mg", q: "What does the Full Code Test require?", a: "All evidence is available, or outstanding evidence is unlikely to affect the outcome" },
  { id: "fc-334", topicId: "case-files-mg", q: "When is the Threshold Test used?", a: "When evidence is still outstanding but seriousness means bail is rejected and an immediate charging decision is needed" },
  { id: "fc-335", topicId: "suspect-interviews", q: "What is a significant statement?", a: "A relevant comment implying guilt — must be recorded and offered for signature" },
  { id: "fc-336", topicId: "suspect-interviews", q: "What is a voluntary interview sometimes called?", a: "Caution Plus Three" },
  { id: "fc-337", topicId: "suspect-interviews", q: "What are the four identification methods in order of preference under Code D?", a: "Video identification, identification parade, group identification, confrontation" },
  { id: "fc-338", topicId: "suspect-interviews", q: "What is the Police and Criminal Evidence Act 1984 caution in full?", a: "You do not have to say anything, but it may harm your defence if you do not mention when questioned something which you later rely on in court; anything you do say may be given in evidence" },
  { id: "fc-339", topicId: "suspect-interviews", q: "When is the now caution used instead of the when questioned caution?", a: "For charging or reporting — not for arrest or interview" },
];

export { FLASHCARDS };
