// ============================================================================
// SHARED — platform-agnostic. Imported by BOTH the web app (app/) and the
// React Native app (native/). Contains NO JSX and no platform APIs.
// Content moved VERBATIM from app/prep-a-constable.jsx — never retyped.
// ============================================================================

const MNEMONICS = [
  { id: "advokate", name: "ADVOKATE", topic: "Identification quality — witness statements & MG11", items: [
    { letter: "A", meaning: "Amount of time the witness observed the suspect" },
    { letter: "D", meaning: "Distance between the witness and the suspect" },
    { letter: "V", meaning: "Visibility — light, weather, time of day" },
    { letter: "O", meaning: "Obstructions to the view" },
    { letter: "K", meaning: "Known — had the witness seen the suspect before?" },
    { letter: "A", meaning: "Any reason to remember the suspect?" },
    { letter: "T", meaning: "Time since the witness last saw the suspect" },
    { letter: "E", meaning: "Errors between the first description and the actual appearance" },
  ], note: "Woven into a witness MG11 wherever identification evidence appears — it tests the reliability of the identification." },
  { id: "tedspie", name: "TEDSPIE", topic: "PEACE interview — Account phase prompts", items: [
    { letter: "T", meaning: "Tell me everything" },
    { letter: "E", meaning: "Explain" },
    { letter: "D", meaning: "Describe" },
    { letter: "S", meaning: "Show me" },
    { letter: "P", meaning: "Precisely" },
    { letter: "I", meaning: "In as much detail as possible" },
    { letter: "E", meaning: "Exactly" },
  ], note: "Used at the Account stage to draw out a free narrative before any clarification or challenge." },
  { id: "eeerr", name: "EEERR", topic: "Quality of the stop & search encounter", items: [
    { letter: "E", meaning: "Engage — approach the person professionally" },
    { letter: "E", meaning: "Explain why you are searching — use GOWISELY and POSH" },
    { letter: "E", meaning: "Ensure it is clear — no jargon" },
    { letter: "R", meaning: "Record — complete the search record form; copy to the person" },
    { letter: "R", meaning: "Reassure — stop and search protects Londoners" },
  ], note: "The 5Es of a quality encounter — how the whole stop & search interaction should be conducted." },
  { id: "pole", name: "POLE", topic: "Intelligence — Management of Police Information", items: [
    { letter: "P", meaning: "Person — the individual linked to the intelligence" },
    { letter: "O", meaning: "Object — vehicle registration, phone number, weapon, or item of property" },
    { letter: "L", meaning: "Location — an address or place linked to the intelligence" },
    { letter: "E", meaning: "Event — the incident or occurrence" },
  ], note: "The entity types intelligence is structured around when recording and searching police information." },
  { id: "scares", name: "SCARES", topic: "Section 17 Police and Criminal Evidence Act 1984 — Powers of entry without warrant", items: [
    { letter: "S", meaning: "Save life or limb / prevent Serious damage to property" },
    { letter: "C", meaning: "Children — recapture a child in police protection" },
    { letter: "A", meaning: "Arrest for an indictable offence" },
    { letter: "R", meaning: "Recapture a person unlawfully at large" },
    { letter: "E", meaning: "Execute an arrest warrant" },
    { letter: "S", meaning: "Specified summary offences (limited list)" },
  ], note: "Section 17 is a power to search for a PERSON, not property — search only where a person could reasonably hide." },
  { id: "idcopplan", name: "IDCOPPLAN", topic: "Section 24 Police and Criminal Evidence Act 1984 — Necessity grounds for arrest (Code G)", items: [
    { letter: "I", meaning: "Investigation — prompt and effective" },
    { letter: "D", meaning: "Disappearance — to prevent it" },
    { letter: "C", meaning: "Child or vulnerable person — to protect" },
    { letter: "O", meaning: "Obstruction of the highway" },
    { letter: "P", meaning: "Physical injury — to prevent" },
    { letter: "P", meaning: "Public decency offence" },
    { letter: "L", meaning: "Loss or damage to property" },
    { letter: "A", meaning: "Address — to confirm" },
    { letter: "N", meaning: "Name — to ascertain" },
  ], note: "Every arrest needs (1) reasonable grounds AND (2) a necessity from this list." },
  { id: "dapbi", name: "DAPBI", topic: "Section 1 Theft Act 1968 — 5 points to prove", items: [
    { letter: "D", meaning: "Dishonestly (Section 2 Theft Act)" },
    { letter: "A", meaning: "Appropriates (Section 3)" },
    { letter: "P", meaning: "Property (Section 4)" },
    { letter: "B", meaning: "Belonging to another (Section 5)" },
    { letter: "I", meaning: "Intention of permanently depriving (Section 6)" },
  ], note: "No theft = no robbery. R v Robinson [1977] — if dishonesty can't be proved, neither can robbery." },
  { id: "wife", name: "WIFE", topic: "Section 10 Theft Act 1968 — Aggravated burglary", items: [
    { letter: "W", meaning: "Weapon of offence — made/adapted/intended to cause injury or incapacitate" },
    { letter: "I", meaning: "Imitation firearm — anything with the appearance of a firearm" },
    { letter: "F", meaning: "Firearm — includes airguns and air pistols" },
    { letter: "E", meaning: "Explosive — manufactured or intended for explosive effect" },
  ], note: "Suspect must have the article WITH HIM at the time of the burglary. Picking one up inside still counts." },
  { id: "die", name: "DIE", topic: "Section 32 Police and Criminal Evidence Act 1984 — Search of person on arrest", items: [
    { letter: "D", meaning: "Danger to anyone (including the suspect)" },
    { letter: "I", meaning: "Implements to escape" },
    { letter: "E", meaning: "Evidence of an offence (any offence)" },
  ], note: "Search of PERSON: evidence of ANY offence. Search of PREMISES under Section 32: evidence of the offence of arrest only, and the offence must be indictable." },
  { id: "file", name: "FILE", topic: "Section 22 Police and Criminal Evidence Act 1984 — Retention of seized items", items: [
    { letter: "F", meaning: "Forensic examination" },
    { letter: "I", meaning: "Investigation" },
    { letter: "L", meaning: "Lawful owner — to establish" },
    { letter: "E", meaning: "Evidence at court — to be produced" },
  ], note: "Items lawfully seized under Section 19 can be retained under Section 22 for any of these purposes." },
  { id: "soap", name: "SOAP", topic: "Section 1 Police and Criminal Evidence Act 1984 — What can be searched for", items: [
    { letter: "S", meaning: "Stolen articles" },
    { letter: "O", meaning: "Offensive weapons" },
    { letter: "A", meaning: "Articles for use in burglary, theft, criminal damage, fraud, TWOC" },
    { letter: "P", meaning: "Pointed or bladed articles (and fireworks)" },
  ], note: "Controlled drugs are NOT covered by Section 1 Police and Criminal Evidence Act 1984 — use Section 23 Misuse of Drugs Act 1971." },
  { id: "gowisely", name: "GOWISELY", topic: "Police and Criminal Evidence Act 1984 Code A — Stop & search information", items: [
    { letter: "G", meaning: "Grounds for the search" },
    { letter: "O", meaning: "Object of the search" },
    { letter: "W", meaning: "Warrant card (if not in uniform)" },
    { letter: "I", meaning: "Identity of the officer" },
    { letter: "S", meaning: "Station the officer is attached to" },
    { letter: "E", meaning: "Entitlement to a copy of the record" },
    { letter: "L", meaning: "Legal power being used" },
    { letter: "Y", meaning: "You are being detained for the purpose of a search" },
  ], note: "Used alongside the 5Es of stop & search: Engage, Explain, Ensure clarity, Record, Reassure." },
  { id: "mai", name: "M-A-I", topic: "Prevention of Crime Act 1953 — Offensive weapon test", items: [
    { letter: "M", meaning: "Made for causing injury (knuckle-duster, flick knife)" },
    { letter: "A", meaning: "Adapted for causing injury (broken bottle, sharpened comb)" },
    { letter: "I", meaning: "Intended by the person to cause injury" },
  ], note: "Public place. Burden shifts to defendant to raise lawful authority or reasonable excuse." },
  { id: "posh", name: "POSH", topic: "Police and Criminal Evidence Act 1984 Code A — Observation for stop & search", items: [
    { letter: "P", meaning: "Paint the picture (briefing, intelligence, context)" },
    { letter: "O", meaning: "Observe (behaviour, body language)" },
    { letter: "S", meaning: "Smell (cannabis, fuel, accelerant)" },
    { letter: "H", meaning: "Hear (admissions, threats, chatter)" },
  ], note: "Helps form the genuine reasonable grounds Code A requires." },
  { id: "no-elbows", name: "NO ELBOWS", topic: "Pocket Notebook / Evidence and Action Book entries — what you must never do", items: [
    { letter: "E", meaning: "Erasures — none. Single line through mistake, initial, continue" },
    { letter: "L", meaning: "Leaves torn out — none. No pages removed from your notebook" },
    { letter: "B", meaning: "Blank spaces — none. No empty gaps to fill in later" },
    { letter: "O", meaning: "Overwriting — none. Do not write over existing words or numbers" },
    { letter: "W", meaning: "Writing in margins / between lines — none. Keep entries clear and chronological" },
    { letter: "S", meaning: "Statements in direct speech — record what is said as close to actual words as possible" },
  ], note: "Governs the integrity of your pocket notebook and Evidence and Action Book entries." },
  { id: "afraid", name: "AFRAID", topic: "Vulnerability / abuse victim assessment", items: [
    { letter: "A", meaning: "Allegation — what is the allegation? Listen to how the victim explains it; spot trivialised abuse" },
    { letter: "F", meaning: "Fear — how does the victim feel? Shaking, loss of speech, fear for others, reprisals" },
    { letter: "R", meaning: "Reluctance — why reluctant to make a statement? Cultural, mistrust, 'normal' to them, repeat history" },
    { letter: "A", meaning: "Adverse — what negative or harmful effect has the victim suffered (including historical)?" },
    { letter: "I", meaning: "Injury — detailed description of ALL injuries: location, age, physical AND mental state" },
    { letter: "D", meaning: "Demeanour — how is the victim presenting? Traumatised, angry, agitated; officer gender preference?" },
  ], note: "Structured way to assess and record a vulnerable or abused victim's account." },
  { id: "safeguard", name: "SAFEGUARD", topic: "Child criminal / sexual exploitation risk", items: [
    { letter: "S", meaning: "Sexual — sexual risk, harm or wellbeing concerns" },
    { letter: "A", meaning: "Absence — absence, truancy or going missing" },
    { letter: "F", meaning: "Family — family and home situation" },
    { letter: "E", meaning: "Emotional — emotional and physical health" },
    { letter: "G", meaning: "Gangs — gangs, street groups, age differential, involvement in crime" },
    { letter: "U", meaning: "Use of technology — use of technology and sexual bullying" },
    { letter: "A", meaning: "Alcohol — alcohol and substances" },
    { letter: "R", meaning: "Receipt — receipt of unexplained gifts or money" },
    { letter: "D", meaning: "Distrust — distrust of authority figures" },
  ], note: "Risk indicators for child criminal and sexual exploitation." },
  { id: "sid", name: "SID", topic: "Section 9(1)(a) Theft Act 1968 — three intents on entry", items: [
    { letter: "S", meaning: "Steal — intent to steal anything in the building or part of the building" },
    { letter: "I", meaning: "Inflict grievous bodily harm — on any person in the building" },
    { letter: "D", meaning: "Do unlawful damage — to the building or anything in it" },
  ], note: "For Section 9(1)(a) burglary the intent must exist at the point of entry as a trespasser." },
  { id: "roast", name: "ROAST", topic: "Presenting a detainee to the custody officer", items: [
    { letter: "R", meaning: "Reasons — full Code G / necessity grounds, complete justification" },
    { letter: "O", meaning: "Offence — the specific offence, full statutory description" },
    { letter: "A", meaning: "Allegation — what the victim or witness has stated" },
    { letter: "S", meaning: "Summary — brief chronological account from first contact to custody" },
    { letter: "T", meaning: "Time and place of arrest — exact time and exact location" },
  ], note: "The structured account you give the custody officer to justify detention." },
  { id: "acecard", name: "ACECARD", topic: "Road traffic collision scene management", items: [
    { letter: "A", meaning: "Approach the scene safely and assess" },
    { letter: "C", meaning: "Caution signs — place warning signs / cones to alert oncoming traffic" },
    { letter: "E", meaning: "Examine the scene — visual assessment of scene and hazards" },
    { letter: "C", meaning: "Casualties — identify and prioritise casualties" },
    { letter: "A", meaning: "Ambulance, fire rescue and other partnership agencies — call in emergency services and partners" },
    { letter: "R", meaning: "Remove obstructions — clear the scene of debris/vehicles where safe" },
    { letter: "D", meaning: "Detailed investigation — statements, evidence, documentation" },
  ], note: "Systematic approach to managing a road traffic collision scene." },
  { id: "abcde", name: "ABCDE", topic: "Detainee risk assessment at custody", items: [
    { letter: "A", meaning: "Appearance — visible injuries? Intoxication? Self-harm? Physical condition on arrival" },
    { letter: "B", meaning: "Behaviour — aggressive? Agitated? Confused? Withdrawn? Compliant?" },
    { letter: "C", meaning: "Communication — coherent? Slurred? Drugs/alcohol? Language barrier? Capacity?" },
    { letter: "D", meaning: "Danger — risk to themselves (self-harm)? Risk to officers or others?" },
    { letter: "E", meaning: "Environment — time of day, vulnerability if bailed, can they get home safely" },
  ], note: "Risk assessment applied when presenting a detainee into custody." },
  { id: "stairs", name: "STAIRS", topic: "Evidence and Action Book recording checklist", items: [
    { letter: "S", meaning: "Statements in direct speech — exact words in quotation marks, never paraphrased" },
    { letter: "T", meaning: "Times — exact times: '14:32', not 'about 2pm'" },
    { letter: "A", meaning: "Actions taken — every action AND why, providing the legal justification" },
    { letter: "I", meaning: "Information given — what information, from whom, at what time, by what means" },
    { letter: "R", meaning: "Referrals — every person you handed information or persons to" },
    { letter: "S", meaning: "Supervisor informed — when you told your supervisor and what direction they gave" },
  ], note: "What a complete Evidence and Action Book entry must capture." },
  { id: "jog", name: "JOG", topic: "Section 32(3) Police and Criminal Evidence Act 1984 — removal of clothing in public", items: [
    { letter: "J", meaning: "Jacket" },
    { letter: "O", meaning: "Outer garment" },
    { letter: "G", meaning: "Gloves" },
  ], note: "In a public place you cannot require removal of more than these. Anything further requires custody conditions (a strip search at the station, not the roadside)." },
  { id: "thrive", name: "THRIVE+", topic: "Risk & vulnerability assessment", items: [
    { letter: "T", meaning: "Threat — what is the threat? To whom? How immediate?" },
    { letter: "H", meaning: "Harm — what harm has been or could be caused?" },
    { letter: "R", meaning: "Risk — how likely is the harm? How serious?" },
    { letter: "I", meaning: "Investigation — what investigative opportunities exist?" },
    { letter: "V", meaning: "Vulnerability — are any persons involved vulnerable?" },
    { letter: "E", meaning: "Engagement — what level of engagement does this require?" },
    { letter: "+", meaning: "Additional considerations — any further factors specific to this incident" },
  ], note: "Used to grade and respond to risk in calls for service." },
  { id: "sara", name: "SARA", topic: "Problem-solving model", items: [
    { letter: "S", meaning: "Scanning — identify and define the problem" },
    { letter: "A", meaning: "Analysis — examine the problem in depth: causes, conditions, patterns" },
    { letter: "R", meaning: "Response — develop and implement responses to address the problem" },
    { letter: "A", meaning: "Assessment — evaluate the effectiveness of the responses" },
  ], note: "The core problem-oriented policing cycle." },
  { id: "rat", name: "RAT", topic: "Routine Activity Theory", items: [
    { letter: "R", meaning: "Routine" },
    { letter: "A", meaning: "Activity" },
    { letter: "T", meaning: "Theory" },
  ], note: "Crime occurs when routine daily activity brings together a motivated offender, a suitable target, and the absence of a capable guardian." },
  { id: "volt", name: "VOLT", topic: "Crime analysis framework", items: [
    { letter: "V", meaning: "Victim — who is the victim? Profile, vulnerability, repeat victimisation?" },
    { letter: "O", meaning: "Offender — who is the offender? Profile, modus operandi, links to other crimes?" },
    { letter: "L", meaning: "Location — where? Hotspot? Repeat location? Environmental factors?" },
    { letter: "T", meaning: "Time — when? Time of day, day of week, seasonal pattern?" },
  ], note: "Framework for analysing the elements of a crime or series." },
  { id: "tile", name: "TILE", topic: "Manual handling risk assessment", items: [
    { letter: "T", meaning: "Task" },
    { letter: "I", meaning: "Individual" },
    { letter: "L", meaning: "Load" },
    { letter: "E", meaning: "Environment" },
  ], note: "Risk assessment for manual handling / lifting under the Manual Handling Operations Regulations 1992. Some versions add O for Other factors (equipment, protective equipment, clothing) — TILEO." },
  { id: "plan", name: "PLAN", topic: "Use of force / interference with a right — justification test", items: [
    { letter: "P", meaning: "Proportionate — no more force than the threat requires; stop when the objective is achieved" },
    { letter: "L", meaning: "Legal — grounded in a lawful power" },
    { letter: "A", meaning: "Accountable — the officer must justify and record it" },
    { letter: "N", meaning: "Necessary — no reasonable alternative in the circumstances" },
  ], note: "The test every use of force — and every interference with a Convention right — must meet. Pairs with the National Decision Model." },
  { id: "ciapoar", name: "CIAPOAR", topic: "National Decision Model — Code of Ethics core", items: [
    { letter: "C", meaning: "Code of Ethics" },
    { letter: "I", meaning: "Identify powers / policy" },
    { letter: "A", meaning: "Aim" },
    { letter: "P", meaning: "Proportionate" },
    { letter: "O", meaning: "Options" },
    { letter: "A", meaning: "Act" },
    { letter: "R", meaning: "Review" },
  ], note: "The mnemonic form of the National Decision Model, with the Code of Ethics at its centre." },
  { id: "ndm", name: "NDM", topic: "National Decision Model — five steps around the Code of Ethics", items: [
    { letter: "1", meaning: "Gather information and intelligence" },
    { letter: "2", meaning: "Assess threat & risk, develop a working strategy" },
    { letter: "3", meaning: "Consider powers and policy" },
    { letter: "4", meaning: "Identify options and contingencies" },
    { letter: "5", meaning: "Take action and review what happened" },
  ], note: "The five stages cycle continuously around the Code of Ethics." },
  { id: "craved", name: "CRAVED", topic: "Hot products — what offenders target", items: [
    { letter: "C", meaning: "Concealable — easy to hide: phones, jewellery, cash" },
    { letter: "R", meaning: "Removable — easy to carry away or move" },
    { letter: "A", meaning: "Available — easy to access or commonly found" },
    { letter: "V", meaning: "Valuable — worth money or useful to the offender" },
    { letter: "E", meaning: "Enjoyable — desirable for personal use, status, or entertainment" },
    { letter: "D", meaning: "Disposable — easy to sell, trade, or get rid of" },
  ], note: "The characteristics that make property attractive to thieves." },
  { id: "dara", name: "DARA", topic: "Domestic abuse risk assessment", items: [
    { letter: "D", meaning: "Domestic — frontline domestic abuse risk assessment tool" },
    { letter: "A", meaning: "Abuse — identifies subtle forms including coercive control" },
    { letter: "R", meaning: "Risk — quality first-responder primary assessment" },
    { letter: "A", meaning: "Assessment — developed by the College of Policing with survivors and frontline officers" },
  ], note: "The first-responder domestic abuse risk assessment tool." },
  { id: "four", name: "FOUR", topic: "Stalking warning signs", items: [
    { letter: "F", meaning: "Fixated — intense unhealthy preoccupation with victim" },
    { letter: "O", meaning: "Obsessive — compulsive and persistent despite warnings" },
    { letter: "U", meaning: "Unwanted — all contact and attention clearly unwelcome" },
    { letter: "R", meaning: "Repeated — occurs on multiple occasions forming a pattern" },
  ], note: "Fixated, Obsessive, Unwanted, Repeated — the hallmark pattern of stalking." },
  { id: "methane", name: "METHANE", topic: "Major incident reporting", items: [
    { letter: "M", meaning: "Major incident declared? — confirm to control room" },
    { letter: "E", meaning: "Exact location — grid reference, address or landmark" },
    { letter: "T", meaning: "Type of incident — road traffic collision, fire, terrorism, etc." },
    { letter: "H", meaning: "Hazards — present or suspected" },
    { letter: "A", meaning: "Access — routes in and out of the scene" },
    { letter: "N", meaning: "Numbers — casualties and types of injury" },
    { letter: "E", meaning: "Emergency services — required at scene" },
  ], note: "The standard structured message for declaring and reporting a major incident." },
  { id: "pens", name: "PENS", topic: "Types of child abuse", items: [
    { letter: "P", meaning: "Physical — hitting, shaking, throwing, poisoning, burning, drowning, suffocating" },
    { letter: "E", meaning: "Emotional — persistent maltreatment; threatening, humiliating, ignoring, isolating" },
    { letter: "N", meaning: "Neglect — persistent failure to meet basic physical/psychological needs" },
    { letter: "S", meaning: "Sexual — forcing/enticing a child into sexual activities, whether aware or not" },
  ], note: "The four recognised categories of child abuse." },
  { id: "pipes", name: "PIPES", topic: "When police complete a report at a road traffic collision", items: [
    { letter: "P", meaning: "Particulars not exchanged — fail to stop AND substantial part or full index obtained" },
    { letter: "I", meaning: "Injury or death — person other than the driver injured or killed" },
    { letter: "P", meaning: "PolCol — police vehicle involved in the collision" },
    { letter: "E", meaning: "Evidence of offences — independent evidence or witness accounts present" },
    { letter: "S", meaning: "Special circumstances — diplomat involved; unusual nature; experts from other agencies present" },
  ], note: "The circumstances in which police complete a formal report at a collision." },
  { id: "primrose", name: "PRIMROSE", topic: "Road traffic collision documentation", items: [
    { letter: "P", meaning: "Position of vehicles — where the vehicles ended up" },
    { letter: "R", meaning: "Record of questions & answers — questions asked and answers received" },
    { letter: "I", meaning: "Information to local authority — damage to fixed property requires notification" },
    { letter: "M", meaning: "Marks and debris on road — skid marks, glass, vehicle parts" },
    { letter: "R", meaning: "Removal of vehicles — recovery arrangements and timings" },
    { letter: "O", meaning: "Offences committed — or alleged at the scene" },
    { letter: "S", meaning: "Supervisor informed — patrol sergeant or duty officer" },
    { letter: "E", meaning: "Exchange of names and addresses — driver details and witness details" },
  ], note: "What to document when investigating a road traffic collision." },
  { id: "rara", name: "RARA", topic: "Domestic abuse risk reduction", items: [
    { letter: "R", meaning: "Remove — arrest or remove the threat to the victim" },
    { letter: "A", meaning: "Avoid — remove the victim from the scenario (e.g. refuge)" },
    { letter: "R", meaning: "Reduce — reduce risk using police, support organisations and charities" },
    { letter: "A", meaning: "Accept — if the victim refuses help after full explanation, accept BUT investigate and consider evidence-led prosecution" },
  ], note: "Options for reducing risk to a domestic abuse victim." },
  { id: "mental-capacity", name: "MENTAL CAPACITY (CURE)", topic: "Mental capacity assessment", items: [
    { letter: "C", meaning: "Communicate — can the person communicate the decision?" },
    { letter: "U", meaning: "Understand — can they understand the information relevant to the decision?" },
    { letter: "R", meaning: "Retain — can they retain the information long enough to decide?" },
    { letter: "E", meaning: "Evaluate — can they use or weigh the information as part of deciding?" },
  ], note: "The functional test of whether a person can make a particular decision." },
];

export { MNEMONICS };
