// ============================================================================
// SHARED — platform-agnostic. Imported by BOTH the web app (app/) and the
// React Native app (native/). Contains NO JSX and no platform APIs.
// Content moved VERBATIM from app/prep-a-constable.jsx — never retyped.
// ============================================================================

const POWER_CATEGORIES = [
  { id: "stop-search", label: "Stop & Search" },
  { id: "entry", label: "Powers of Entry" },
  { id: "arrest", label: "Powers of Arrest" },
  { id: "seizure", label: "Seizure" },
  { id: "detention", label: "Detention" },
  { id: "mental-health", label: "Mental Health" },
  { id: "traffic", label: "Traffic & Roadside" },
];

const POWERS = [
  // ─────────── STOP & SEARCH ───────────
  {
    id: "s1-pace",
    title: "Stop & Search — Stolen / Prohibited",
    section: "Section 1",
    act: "Police and Criminal Evidence Act 1984",
    category: "stop-search",
    grounds: "Reasonable grounds to suspect person/vehicle is carrying stolen or prohibited articles (stolen goods, offensive weapons, articles for theft, burglary, taking a conveyance without consent, fraud or criminal damage, and pointed or bladed articles)",
    where: "Any place to which the public have access (or to which person has gone uninvited)",
    mnemonic: "GOWISELY",
    notes: "Grounds, Object, Warrant card, Identity, Station, Entitlement to a record, Legal power, You are detained. Reasonable force under Section 117. Outer clothing only in public (Section 2(9)). Receipt to be given.",
  },
  {
    id: "s23-moda",
    title: "Stop & Search — Drugs",
    section: "Section 23",
    act: "Misuse of Drugs Act 1971",
    category: "stop-search",
    grounds: "Reasonable grounds to suspect person is in possession of a controlled drug",
    where: "Any place",
    mnemonic: "Same GOWISELY framework",
    notes: "Distinct power from Section 1 Police and Criminal Evidence Act 1984. Use this when grounds relate to drugs. Records required under Police and Criminal Evidence Act 1984 Code A.",
  },
  {
    id: "s60-cjpoa",
    title: "Stop & Search — Section 60 Authorisation",
    section: "Section 60",
    act: "Criminal Justice and Public Order Act 1994",
    category: "stop-search",
    grounds: "NO individual grounds required. Inspector+ authorisation for a specified locality where reasonable belief that serious violence may take place / persons carrying offensive weapons / incidents involving same",
    where: "Within the specified locality during the authorised period",
    mnemonic: "—",
    notes: "Suspicionless power within authorisation. Pre-authorisation by Inspector (must be confirmed by Superintendent if extended). Time-limited (up to 24h, extendable +24h). Body Worn Video activation expected. Subject to enhanced scrutiny.",
  },
  {
    id: "s47a-terrorism",
    title: "Stop & Search — Terrorism",
    section: "Section 47A",
    act: "Terrorism Act 2000",
    category: "stop-search",
    grounds: "NO individual grounds required. Authorisation by Assistant Chief Constable / Commander+ where reasonable suspicion that act of terrorism will take place AND authorisation is necessary to prevent it",
    where: "Within the authorised area for the authorised period (max 14 days)",
    mnemonic: "—",
    notes: "Replaced the old Section 44. Strict statutory thresholds. Use in counter-terrorism operations only; rare in everyday policing.",
  },

  // ─────────── ENTRY ───────────
  {
    id: "s17-pace",
    title: "Entry without Warrant",
    section: "Section 17",
    act: "Police and Criminal Evidence Act 1984",
    category: "entry",
    grounds: "Five categories: save life or limb / prevent serious damage to property; capture (arrest of an escapee unlawfully at large); arrest for an indictable offence; re-arrest of a detainee unlawfully at large; execute a warrant of arrest or commitment, or recapture a child at risk",
    where: "Any premises (including vehicles)",
    mnemonic: "SCARES",
    notes: "MUST believe person is on the premises (except 'save life or limb'/prevent serious damage). Reasonable force under Section 117. Search confined to area for which power exercised (Section 17(4)).",
  },
  {
    id: "s18-pace",
    title: "Entry after Arrest (Same Offence)",
    section: "Section 18",
    act: "Police and Criminal Evidence Act 1984",
    category: "entry",
    grounds: "Person under arrest for INDICTABLE offence; reasonable grounds to believe premises contain evidence relating to that offence OR a connected/similar offence",
    where: "Premises OCCUPIED OR CONTROLLED by the arrested person",
    mnemonic: "—",
    notes: "Inspector+ authorisation IN WRITING required (Section 18(4)). Section 18(5) allows search BEFORE authorisation where presence of arrestee necessary for effective investigation — but Inspector must be told ASAP.",
  },
  {
    id: "s32-pace-premises",
    title: "Entry after Arrest (Premises Suspect Was At)",
    section: "Section 32(2)(b)",
    act: "Police and Criminal Evidence Act 1984",
    category: "entry",
    grounds: "Arrested for INDICTABLE offence; reasonable grounds to believe evidence on those premises that relates to offence of arrest",
    where: "Premises the person was IN when arrested OR IMMEDIATELY BEFORE arrest",
    mnemonic: "—",
    notes: "No Inspector authority needed (unlike Section 18). But narrower — only the offence of arrest, not similar/connected. Must search immediately or soon after arrest.",
  },
  {
    id: "warrant-s8-pace",
    title: "Search Warrant (Section 8 Police and Criminal Evidence Act 1984)",
    section: "Section 8",
    act: "Police and Criminal Evidence Act 1984",
    category: "entry",
    grounds: "Magistrate satisfied: reasonable grounds for believing indictable offence committed; material likely to be on the premises; relevant evidence; would be admissible; AND one of the access conditions met (cannot obtain consent, would prejudice, etc.)",
    where: "Premises specified on the warrant",
    mnemonic: "—",
    notes: "Section 15 (warrant application) and Section 16 (warrant execution) must be complied with. Failures = unlawful warrant. Police and Criminal Evidence Act 1984 Code B governs.",
  },

  // ─────────── ARREST ───────────
  {
    id: "s24-pace",
    title: "Arrest without Warrant",
    section: "Section 24",
    act: "Police and Criminal Evidence Act 1984",
    category: "arrest",
    grounds: "TWO elements: (1) reasonable grounds to suspect involvement/committing/about to commit ANY offence, AND (2) reasonable grounds to believe arrest is necessary",
    where: "Anywhere",
    mnemonic: "IDCOPPLAN",
    notes: "Necessity grounds: Investigation, Disappearance, Child/vulnerable, Obstruction of highway, Physical injury, Public decency, Loss/damage property, Address (ascertain), Name (ascertain). Caution + Reason for arrest required (Section 28). Code G applies.",
  },
  {
    id: "s24a-pace",
    title: "Citizen's Arrest",
    section: "Section 24A",
    act: "Police and Criminal Evidence Act 1984",
    category: "arrest",
    grounds: "Indictable offence; reasonable grounds to believe arrest necessary to prevent: physical injury, loss/damage to property, person making off before constable can assume responsibility for them",
    where: "Anywhere",
    mnemonic: "—",
    notes: "Available to ANY person — not police. INDICTABLE offences only (not summary). Constable must be present/able to take over within reasonable time. Common in retail security / store detective context.",
  },
  {
    id: "breach-peace",
    title: "Breach of the Peace",
    section: "Common law",
    act: "Common Law",
    category: "arrest",
    grounds: "Breach of the peace is taking place / has taken place in officer's presence / is likely to be renewed; OR person is going to commit a breach in officer's presence",
    where: "Anywhere — including private premises",
    mnemonic: "—",
    notes: "Not an offence; a power to detain. Must release ONCE the threat has passed. Common in domestic incidents where no specific offence yet. Imminent breach required.",
  },

  // ─────────── SEIZURE ───────────
  {
    id: "s19-pace",
    title: "Seizure (General)",
    section: "Section 19",
    act: "Police and Criminal Evidence Act 1984",
    category: "seizure",
    grounds: "Constable LAWFULLY on premises; reasonable grounds to believe item: (a) obtained in consequence of offence, OR (b) evidence of any offence; AND necessary to seize to prevent concealment/loss/damage/destruction/alteration",
    where: "Premises on which constable is lawfully present",
    mnemonic: "FILE (retention)",
    notes: "Broad seizure — ANY offence. Section 21 right of access; Section 22 retention (retained for forensic examination, investigation, a linked offence, or as evidence). Section 19(3) covers items needed as evidence; Section 19(2) covers items obtained from offence.",
  },
  {
    id: "s22-pace",
    title: "Retention of Seized Items",
    section: "Section 22",
    act: "Police and Criminal Evidence Act 1984",
    category: "seizure",
    grounds: "Items lawfully seized may be retained for so long as necessary",
    where: "—",
    mnemonic: "FILE",
    notes: "Items may be retained for forensic examination, investigation, a linked offence, or as evidence at court. Items must be returned once retention no longer justified. Police and Criminal Evidence Act 1984 Code B governs.",
  },
  {
    id: "s165a-rta",
    title: "Seize Vehicle — No Insurance / Licence",
    section: "Section 165A",
    act: "Road Traffic Act 1988",
    category: "seizure",
    grounds: "Constable in uniform; reasonable grounds to believe vehicle being driven without insurance (Section 143) OR without licence in accordance with which it is being driven (Section 87)",
    where: "Road or other public place",
    mnemonic: "—",
    notes: "Driver given chance to produce documents within a reasonable time first. Refusal/failure → seizure. Use of reasonable force. Section 165B governs the seizure process.",
  },
  {
    id: "s59-pra",
    title: "Seize Vehicle — Anti-Social Use",
    section: "Section 59",
    act: "Police Reform Act 2002",
    category: "seizure",
    grounds: "Constable in uniform; reasonable grounds to believe vehicle being used in manner contravening Section 3 or Section 34 Road Traffic Act 1988 AND causing/likely to cause alarm/distress/annoyance to public",
    where: "Anywhere",
    mnemonic: "Warn first, then seize",
    notes: "Warning first on first occasion (unless impracticable or prior warning within 12 months for vehicle/driver). PNC record. Seizure on subsequent occasion within 12 months without further warning. Reasonable force permitted.",
  },

  // ─────────── DETENTION ───────────
  {
    id: "s37-pace",
    title: "Custody Detention",
    section: "Section 37",
    act: "Police and Criminal Evidence Act 1984",
    category: "detention",
    grounds: "Custody officer decides whether sufficient evidence to charge. If insufficient: detention authorised only if necessary to secure/preserve evidence OR obtain by questioning",
    where: "Designated police station",
    mnemonic: "—",
    notes: "Custody officer (Sergeant+) is gatekeeper, independent of investigation. Police and Criminal Evidence Act 1984 Code C applies. Initial 24 hours from relevant time; extension to 36h (Superintendent, indictable); further to 96h (magistrates' warrant). Terrorism: separate longer schedule.",
  },
  {
    id: "s40-pace",
    title: "Review of Detention",
    section: "Section 40",
    act: "Police and Criminal Evidence Act 1984",
    category: "detention",
    grounds: "Reviews carried out by review officer (Inspector+ if not yet charged; custody officer if charged)",
    where: "Designated police station",
    mnemonic: "—",
    notes: "First review within 6 hours; second within 9 hours of first; thereafter every 9 hours max. Detainee/solicitor may make representations. Reviews can be on-screen / via video / by phone in some cases (Section 40A/40B).",
  },

  // ─────────── MENTAL HEALTH ───────────
  {
    id: "s136-mha",
    title: "Removal from a Public Place",
    section: "Section 136",
    act: "Mental Health Act 1983",
    category: "mental-health",
    grounds: "Constable finds a person in a place to which the public have access who appears to be suffering from a mental disorder and to be in immediate need of care or control. The constable may, if they think it necessary in the interests of that person or for the protection of others, remove them to (or keep them at) a place of safety.",
    where: "Any place EXCEPT a private dwelling (the person's or another's home / its associated living accommodation). Includes streets, shops, vehicles, communal areas, workplaces, A&E, police station front counter.",
    mnemonic: "Consult a health professional first where practicable",
    notes: "Before using Section 136, the constable must (if practicable) consult a registered medical practitioner, registered nurse, approved mental health professional or paramedic. A police station may only be used as a place of safety for adults in exceptional 'specified risk' circumstances (regulations) and NEVER for under-18s. Detention period: up to 24 hours (extendable by 12 hours on medical grounds). Purpose is assessment, not punishment — it is not an arrest. Related: Section 136C gives a power to SEARCH the detained person, and Section 136C(6) the power to RETAIN items found (see separate cards).",
  },
  {
    id: "s136c-mha",
    title: "Search of Detained Person",
    section: "Section 136C",
    act: "Mental Health Act 1983",
    category: "mental-health",
    grounds: "Where a person is detained under Section 135 or Section 136, a constable may search them if the constable has reasonable grounds for believing that the person may present a danger to themselves or others AND is concealing on them something that could be used to cause physical injury to themselves or others. There is also power to search for items that could be used to assist escape.",
    where: "Wherever the person is detained (en route to or at the place of safety).",
    mnemonic: "Danger + concealed item = search",
    notes: "Inserted by the Policing and Crime Act 2017. The search may be only to the extent reasonably required to find the item, and does not authorise removal of clothing in public other than outer coat, jacket and gloves. A constable may use reasonable force. This is a protective search, not an evidential one.",
  },
  {
    id: "s136c6-mha",
    title: "Retention of Seized Items",
    section: "Section 136C(6)",
    act: "Mental Health Act 1983",
    category: "mental-health",
    grounds: "Anything found on a Section 136C search which the constable reasonably believes the person might use to cause physical injury to themselves or others may be SEIZED and RETAINED.",
    where: "Wherever the search takes place.",
    mnemonic: "Seize what could cause injury",
    notes: "The retention power is limited to items posing a risk of physical injury. Retained property must be handled and returned in accordance with force policy once the risk has passed. Works alongside the Section 136C search power.",
  },
  {
    id: "s135-mha",
    title: "Warrant to Enter & Remove",
    section: "Section 135(1)",
    act: "Mental Health Act 1983",
    category: "mental-health",
    grounds: "On information on oath from an Approved Mental Health Professional (AMHP), a magistrate may issue a warrant authorising a constable to enter premises (using force if need be) and remove a person believed to be suffering from a mental disorder who is being ill-treated/neglected/not kept under proper control, or is unable to care for themselves and living alone, to a place of safety.",
    where: "The private premises specified in the warrant (this is the route into a dwelling, which Section 136 cannot reach).",
    mnemonic: "AMHP + warrant; constable must be accompanied",
    notes: "The constable executing the warrant must be accompanied by an AMHP and a registered medical practitioner. Section 135(2) is a separate warrant to retake a patient already liable to be detained (e.g. recalled). This is how mental-health removal reaches inside a home — Section 136 is for public places only.",
  },
  {
    id: "s5-4-mha",
    title: "Nurse's Holding Power",
    section: "Section 5(4)",
    act: "Mental Health Act 1983",
    category: "mental-health",
    grounds: "A registered mental health or learning disability nurse may detain a voluntary in-patient already receiving treatment for mental disorder, where it appears the patient is suffering from a mental disorder to such a degree that it is necessary for their health/safety or others' protection to be immediately restrained from leaving, and it is not practicable to secure a doctor's attendance to use Section 5(2).",
    where: "A hospital (in-patient setting).",
    mnemonic: "Nurse = 6 hours",
    notes: "Lasts up to 6 hours, or until a doctor able to use Section 5(2) arrives, whichever is earlier. Context power for officers — useful to understand when called to a hospital. Police have no role in exercising it but may be asked to assist with an absconding patient.",
  },
  {
    id: "s5-2-mha",
    title: "Doctor's Holding Power",
    section: "Section 5(2)",
    act: "Mental Health Act 1983",
    category: "mental-health",
    grounds: "The registered medical practitioner (or approved clinician) in charge of a voluntary in-patient's treatment may furnish a report detaining them where it appears an application for compulsory admission ought to be made.",
    where: "A hospital (in-patient setting).",
    mnemonic: "Doctor = 72 hours",
    notes: "Lasts up to 72 hours, allowing time for a full Mental Health Act assessment. Like Section 5(4), this is a clinical power, not a police one — included so officers understand the framework when attending hospitals.",
  },
  {
    id: "s18-mha",
    title: "Return of AWOL Patient",
    section: "Section 18 / 138",
    act: "Mental Health Act 1983",
    category: "mental-health",
    grounds: "A patient who is liable to be detained and is absent without leave (AWOL) — has left hospital without permission or failed to return — may be taken into custody and returned by a constable, AMHP, hospital staff, or anyone authorised by the hospital managers.",
    where: "Anywhere (Section 138 allows retaking).",
    mnemonic: "AWOL detained patient → retake & return",
    notes: "Applies to patients already liable to detention under the Act, not voluntary patients. Time limits on retaking depend on the detention section. Often actioned by police on a 'failed to return from leave' report. Distinct from Section 136 (which is for undetained persons in public).",
  },
  {
    id: "s64a-photograph",
    title: "Power to Take a Roadside Photograph",
    section: "Section 64A",
    act: "Police and Criminal Evidence Act 1984",
    category: "traffic",
    grounds: "A constable may take a photograph at the roadside for a number of reasons, including that the person is being reported for a traffic offence.",
    where: "At the roadside.",
    mnemonic: "—",
    notes: "Section 64A(1B) — the photograph power itself. Section 64A(2) — a constable may lawfully require the removal of any item or substance obstructing the taking of the photograph. Section 117 — reasonable force may be used to exercise this power.",
  },
];

// ============================================================
// TOR CODES — Met Traffic Offence Report codes (Form 4740 endorsable,
// Form 4741 non-endorsable). What an officer writes ON THE TICKET.
// Distinct from the DVLA endorsement codes (SP30, CU80, etc.) used in the
// OFFENCES entries above, which is what appears on the DRIVER'S LICENCE.
// Source: physical MPS 4740 (Oct 2018) / 4741 (June 2018) TOR code cards
// supplied by Mr Mansur. Two codes on 4741 (marked "300?"/"301?") were
// physically torn on the source card — the statute and wording are legible
// but the exact code number is not confirmed. "430b"/"433b"/"299b" are the
// SAME code repeated a second time on the source card in a different
// section; kept distinct here so both printed wordings are preserved.

export { POWER_CATEGORIES, POWERS };
