// ============================================================================
// SHARED — platform-agnostic. Imported by BOTH the web app (app/) and the
// React Native app (native/). Contains NO JSX and no platform APIs.
// Content moved VERBATIM from app/prep-a-constable.jsx — never retyped.
// ============================================================================

const TOPICS = [
  { id: "pace-1984", studyWeek: 5, title: "Police and Criminal Evidence Act 1984", shortTitle: "Police and Criminal Evidence Act 1984", description: "Stop & search, entry, arrest, search after arrest, seizure, detention.", accent: "#1A3A6C" },
  { id: "theft-act-1968", studyWeek: 4, title: "Theft Act 1968", shortTitle: "Theft Act 1968", description: "Theft, robbery, burglary, aggravated burglary, TWOC, going equipped.", accent: "#7C2D2D" },
  { id: "moda-1971", studyWeek: 5, title: "Misuse of Drugs Act 1971", shortTitle: "Misuse of Drugs Act 1971", description: "Drug classes, Section 4 production & supply, Section 5 possession & PWITS, Section 23 search.", accent: "#5C2E7C" },
  { id: "poca-1953", studyWeek: 5, title: "Prevention of Crime Act 1953", shortTitle: "Prevention of Crime Act 1953", description: "Offensive weapons in public — Section 1 possession, Section 1A threatening, M-A-I test.", accent: "#1F5F4D" },
  { id: "cja-1988", studyWeek: 5, title: "Criminal Justice Act 1988", shortTitle: "Criminal Justice Act 1988", description: "Bladed articles — Section 139 in public, Section 139A education, Section 139AA threatening, Section 139B entry.", accent: "#9A4B14" },
  { id: "owa-2019", studyWeek: 5, title: "Offensive Weapons Act 2019", shortTitle: "Offensive Weapons Act 2019", description: "Corrosives (Section 6), flick/gravity knives (Section 44), prohibited weapons in private (Section 46, Section 52).", accent: "#3C5A8C" },
  { id: "suspect-interviews", studyWeek: 9, title: "Suspect Interviews & PEACE", shortTitle: "Suspect Interviews & PEACE", description: "PEACE model, TEDSPIE, active listening, caution, no ELBOWS for spontaneous comments.", accent: "#2F6E5C" },
  { id: "mg11", studyWeek: 5, title: "MG11 Witness Statements", shortTitle: "MG11 Witness Statements", description: "Writing rules, ELBOWS, 24-hour clock, the 5 parts of a statement.", accent: "#8C4F1F" },
  { id: "intelligence-mopi", studyWeek: 5, title: "Intelligence & Management of Police Information", shortTitle: "Intelligence & Management of Police Information", description: "3×5×2 grading, POLE, Golden Hour, National Intelligence Model, Management of Police Information principles.", accent: "#4A3A8C" },
  { id: "cpia-1996", studyWeek: 11, title: "Criminal Procedure & Investigations Act 1996", shortTitle: "Criminal Procedure & Investigations Act 1996", description: "Disclosure, the 4 Rs (Record, Retain, Review, Reveal), MG6 series, sensitive material.", accent: "#7A2D5C" },
  { id: "crim-damage-1971", studyWeek: 10, title: "Criminal Damage Act 1971", shortTitle: "Criminal Damage Act 1971", description: "Basic criminal damage (Section 1(1)), aggravated criminal damage (Section 1(2)), arson, threats, possession with intent.", accent: "#B5391B" },
  { id: "crim-attempts-1981", studyWeek: 10, title: "Criminal Attempts Act 1981", shortTitle: "Criminal Attempts Act 1981", description: "Section 9 vehicle interference - interfering with a vehicle, trailer, or its contents with intent.", accent: "#3F6E3F" },
  { id: "asbcp-2014", studyWeek: 11, title: "Anti-social Behaviour, Crime and Policing Act 2014", shortTitle: "Anti-social Behaviour, Crime and Policing Act 2014", description: "Section 34 dispersal power, exemptions, CPN, CBO, PSPO, closure powers.", accent: "#B8721E" },
  { id: "poa-1986", studyWeek: 12, title: "Public Order Act 1986", shortTitle: "Public Order Act 1986", description: "Section 4 (fear/provocation of violence), Section 4A (intentional harassment), Section 5 (harassment/alarm/distress).", accent: "#7B1F5C" },
  { id: "fraud-act-2006", studyWeek: 12, title: "Fraud Act 2006", shortTitle: "Fraud Act 2006", description: "Section 1 fraud, Section 2 false representation, Section 3 failing to disclose, Section 4 abuse of position, Section 6 articles.", accent: "#1E5F8C" },
  { id: "pra-2002", studyWeek: 11, title: "Police Reform Act 2002", shortTitle: "Police Reform Act 2002", description: "Section 59 - stop, warn and seize vehicles used in anti-social manner.", accent: "#5C5C1F" },
  { id: "prsra-2011", studyWeek: 12, title: "Police Reform & Social Responsibility Act 2011", shortTitle: "Police Reform & Social Responsibility Act 2011", description: "Section 34 - duty of PCCs and chief constables to engage with the public.", accent: "#1F5C5C" },
  { id: "rta-1988", studyWeek: 11, title: "Road Traffic Act 1988", shortTitle: "Road Traffic Act 1988", description: "Stop powers (Section 163/164/165), drink/drug testing (Section 6), dangerous & careless driving, document offences.", accent: "#8C3F1E" },
  { id: "oap-1861", studyWeek: 14, title: "Offences Against the Person", shortTitle: "Offences Against the Person", description: "Assault ladder: common assault (Section 39 Criminal Justice Act 1988), ABH (Section 47), GBH/wounding (Section 20), GBH with intent (Section 18), emergency workers, Section 89 Police Act 1996, defences.", accent: "#7C1F1F" },
  { id: "soa-2003", studyWeek: 15, title: "Sexual Offences Act 2003 — Consent", shortTitle: "Sexual Offences Act 2003 — Consent", description: "Age of consent (16 / under 13), Section 5 rape of child under 13, Section 74 conditional consent (choice & freedom), Section 75 evidential presumptions (rebuttable), Section 76 conclusive presumptions (unrebuttable).", accent: "#5C1F5C" },
  { id: "vulnerability", studyWeek: 14, title: "Vulnerability & Risk", shortTitle: "Vulnerability & Risk", description: "College of Policing definition, Care Act 2014 Section 42, three vulnerability factors, six safeguarding principles, ABCDE assessment, AFRAID, 123 reporting, types of abuse, Section 76 Serious Crime Act 2015.", accent: "#1F5C3F" },
  { id: "da-protective", studyWeek: 14, title: "Domestic Abuse — Protective Measures", shortTitle: "Domestic Abuse — Protective Measures", description: "DVPN, DVPO, Non-Molestation Order, Restraining Order, DAPN/DAPO, Domestic Violence Disclosure Scheme, DA Act 2021 definition, Section 70 non-fatal strangulation, DARA, RARA, evidence-led prosecution.", accent: "#7C1F4F" },
  { id: "rr-aggravated", studyWeek: 16, title: "Racially & Religiously Aggravated Offences", shortTitle: "Racially & Religiously Aggravated Offences", description: "Section 28 Crime and Disorder Act 1998 (definition), Sections 29–32 aggravated offences, Section 66 Sentencing Act 2020 (all offences), hate crime vs hate incident, timing of hostility, stirring up hatred.", accent: "#4F1F7C" },
  { id: "missing-persons", studyWeek: 15, title: "Missing Persons — Initial Powers", shortTitle: "Missing Persons — Initial Powers", description: "Risk levels, Section 17 and Section 117 Police and Criminal Evidence Act 1984, Section 46 Children Act 1989 (police protection, no force), Section 135/136 Mental Health Act 1983, Mental Capacity Act 2005, bespoke investigation.", accent: "#1F4F7C" },
  { id: "disputes-noncrime", studyWeek: 14, title: "Dealing with Disputes & Non-Crime Incidents", shortTitle: "Disputes & Non-Crime Incidents", description: "Breach of the peace, five building blocks of investigation, civil trespass, landlord/tenant, bailiffs, main responsibilities (preserve, investigate, impartial, record).", accent: "#3F5C2E" },
  { id: "case-files-mg", studyWeek: 14, title: "Case Files & MG Forms", shortTitle: "Case Files & MG Forms", description: "DG6, National File Standard, Full Code Test vs Threshold Test, MG0–MG22, MG3 contents, MG5, MG6 series (disclosure), used vs unused material, three unused material assessment answers.", accent: "#5C3F1F" },
  { id: "pha-1997", studyWeek: 15, title: "Protection from Harassment Act 1997", shortTitle: "Protection from Harassment Act 1997", description: "Course of conduct, Section 2 harassment, Section 2A stalking, Section 4 fear of violence, Section 4A stalking with fear or serious alarm, defences, restraining orders on conviction and acquittal.", accent: "#6B2D5C" },
  { id: "special-measures", studyWeek: 15, title: "Special Measures — Youth Justice and Criminal Evidence Act 1999", shortTitle: "Special Measures", description: "Section 16 vulnerable and Section 17 intimidated witnesses, the measures in Sections 23–30 (screens, live link, video evidence, intermediaries), who applies and how, the MG2.", accent: "#2D5C6B" },
  { id: "vps", studyWeek: 15, title: "Victim Personal Statements", shortTitle: "Victim Personal Statements", description: "Right 7 of the Victims' Code — the victim's account of impact: who takes it, what it can and cannot contain, the victim's choices, disclosure, and how the court uses it at sentencing.", accent: "#5C6B2D" },
  { id: "ap1-ethics", studyWeek: 2, title: "Ethics & Professional Standards", shortTitle: "Ethics & Professional Standards", description: "Code of Ethics 2024 (Courage, Respect and empathy, Public service), the statutory Code of Practice for Ethical Policing 2023, the ten Standards of Professional Behaviour, misconduct vs gross misconduct.", accent: "#1F3A5C" },
  { id: "ap1-met-london", studyWeek: 2, title: "New Met for London & Peelian Principles", shortTitle: "New Met for London & Peel", description: "The Casey Review and Turnaround Plan, the mission (More Trust, Less Crime, High Standards), the three pillars, Phase 2, and the nine Peelian principles of policing by consent.", accent: "#8C2B2B" },
  { id: "ap1-models", studyWeek: 2, title: "Decision Models — NDM, Procedural Justice & Quality Encounter", shortTitle: "Decision & Encounter Models", description: "The National Decision Model (CIAPOAR) with the Code of Ethics at its centre, the four principles of procedural justice, and the Met's Quality of Encounter model for stop and search.", accent: "#2B8C6B" },
  { id: "ap1-force", studyWeek: 2, title: "Use of Force & Manual Handling", shortTitle: "Use of Force & Manual Handling", description: "Section 3 Criminal Law Act 1967, Section 117 Police and Criminal Evidence Act 1984, common law, Articles 2 and 3, the PLAN justification test, and TILE manual handling assessment.", accent: "#8C5A2B" },
  { id: "ap1-equality-hr", studyWeek: 3, title: "Equality Act 2010 & Human Rights", shortTitle: "Equality & Human Rights", description: "The nine protected characteristics, prohibited conduct, the Public Sector Equality Duty, and the key Convention Articles for policing — absolute, limited and qualified rights.", accent: "#5C2B8C" },
  { id: "ap1-victims-pnb", studyWeek: 1, title: "Victims' Code 2021 & Pocketbook Rules", shortTitle: "Victims' Code & Pocketbook", description: "The 12 rights of the Victims' Code, enhanced rights and timescales, who counts as a victim, and the evidential rules for the pocket notebook.", accent: "#2B6B8C" },
];

// Each AP mock draws ONLY from the topics listed for that assessment point in the
// Assessment Points Topics document — nothing else.

const EXAM_CONFIGS = {
  AP1: { label: "AP1", questions: 20, durationMins: 30, passMark: 0.6,
    topicIds: ["ap1-ethics", "ap1-met-london", "ap1-models", "ap1-force", "ap1-equality-hr", "ap1-victims-pnb"] },
  AP2: { label: "AP2", questions: 40, durationMins: 60, passMark: 0.6,
    topicIds: ["pace-1984", "theft-act-1968", "moda-1971", "cja-1988", "poca-1953", "suspect-interviews", "intelligence-mopi", "mg11"] },
  AP3: { label: "AP3", questions: 40, durationMins: 60, passMark: 0.6,
    topicIds: ["rta-1988", "pace-1984", "theft-act-1968", "crim-damage-1971", "crim-attempts-1981", "asbcp-2014", "poa-1986", "fraud-act-2006", "cpia-1996", "pra-2002", "prsra-2011", "case-files-mg", "disputes-noncrime", "suspect-interviews", "vps"] },
  AP4: { label: "AP4", questions: 40, durationMins: 60, passMark: 0.6,
    topicIds: ["missing-persons", "da-protective", "vulnerability", "soa-2003", "rr-aggravated", "case-files-mg", "moda-1971", "pace-1984", "theft-act-1968", "cja-1988", "poca-1953", "fraud-act-2006", "crim-damage-1971", "rta-1988", "oap-1861", "pha-1997", "special-measures", "vps"] },
};

export { TOPICS, EXAM_CONFIGS };
